INSERT INTO brand (name) VALUES ('Abarth');
INSERT INTO model (brand_id, name) VALUES (1, '500');
INSERT INTO model (brand_id, name) VALUES (1, '595');
INSERT INTO model (brand_id, name) VALUES (1, '695');
INSERT INTO model (brand_id, name) VALUES (1, 'Grande Punto');
INSERT INTO brand (name) VALUES ('Acura');
INSERT INTO model (brand_id, name) VALUES (2, 'CL');
INSERT INTO model (brand_id, name) VALUES (2, 'MDX');
INSERT INTO model (brand_id, name) VALUES (2, 'RL');
INSERT INTO model (brand_id, name) VALUES (2, 'TL');
INSERT INTO model (brand_id, name) VALUES (2, 'ZDX');
INSERT INTO brand (name) VALUES ('Aixam');
INSERT INTO model (brand_id, name) VALUES (3, 'A721');
INSERT INTO model (brand_id, name) VALUES (3, 'A741');
INSERT INTO model (brand_id, name) VALUES (3, 'A751');
INSERT INTO model (brand_id, name) VALUES (3, 'City');
INSERT INTO model (brand_id, name) VALUES (3, 'Coupe');
INSERT INTO model (brand_id, name) VALUES (3, 'Crossline');
INSERT INTO model (brand_id, name) VALUES (3, 'Crossover');
INSERT INTO model (brand_id, name) VALUES (3, 'GTO');
INSERT INTO model (brand_id, name) VALUES (3, 'Roadline');
INSERT INTO model (brand_id, name) VALUES (3, 'Scouty');
INSERT INTO model (brand_id, name) VALUES (3, 'Scouty R');
INSERT INTO brand (name) VALUES ('Alfa Romeo');
INSERT INTO model (brand_id, name) VALUES (4, '4C');
INSERT INTO model (brand_id, name) VALUES (4, '33');
INSERT INTO model (brand_id, name) VALUES (4, '75');
INSERT INTO model (brand_id, name) VALUES (4, '90');
INSERT INTO model (brand_id, name) VALUES (4, '145');
INSERT INTO model (brand_id, name) VALUES (4, '147');
INSERT INTO model (brand_id, name) VALUES (4, '155');
INSERT INTO model (brand_id, name) VALUES (4, '156');
INSERT INTO model (brand_id, name) VALUES (4, '164');
INSERT INTO model (brand_id, name) VALUES (4, '166');
INSERT INTO model (brand_id, name) VALUES (4, 'Alfasud');
INSERT INTO model (brand_id, name) VALUES (4, 'Alfetta');
INSERT INTO model (brand_id, name) VALUES (4, 'Brera');
INSERT INTO model (brand_id, name) VALUES (4, 'Crosswagon');
INSERT INTO model (brand_id, name) VALUES (4, 'Giulia');
INSERT INTO model (brand_id, name) VALUES (4, 'Giullietta');
INSERT INTO model (brand_id, name) VALUES (4, 'GT');
INSERT INTO model (brand_id, name) VALUES (4, 'GTV');
INSERT INTO model (brand_id, name) VALUES (4, 'Mito');
INSERT INTO model (brand_id, name) VALUES (4, 'RS');
INSERT INTO model (brand_id, name) VALUES (4, 'Spider');
INSERT INTO model (brand_id, name) VALUES (4, 'Sportwagon');
INSERT INTO model (brand_id, name) VALUES (4, 'Sprint');
INSERT INTO model (brand_id, name) VALUES (4, 'Stelvio');
INSERT INTO brand (name) VALUES ('Alpine');
INSERT INTO model (brand_id, name) VALUES (5, 'A110');
INSERT INTO model (brand_id, name) VALUES (5, 'A310');
INSERT INTO model (brand_id, name) VALUES (5, 'V6');
INSERT INTO brand (name) VALUES ('Aston Martin');
INSERT INTO model (brand_id, name) VALUES (6, 'Bulldog');
INSERT INTO model (brand_id, name) VALUES (6, 'Cygnet');
INSERT INTO model (brand_id, name) VALUES (6, 'DB');
INSERT INTO model (brand_id, name) VALUES (6, 'DB1');
INSERT INTO model (brand_id, name) VALUES (6, 'DB2');
INSERT INTO model (brand_id, name) VALUES (6, 'DB4');
INSERT INTO model (brand_id, name) VALUES (6, 'DB5');
INSERT INTO model (brand_id, name) VALUES (6, 'DB6');
INSERT INTO model (brand_id, name) VALUES (6, 'DB7');
INSERT INTO model (brand_id, name) VALUES (6, 'DB9');
INSERT INTO model (brand_id, name) VALUES (6, 'DB11');
INSERT INTO model (brand_id, name) VALUES (6, 'DB Mk III');
INSERT INTO model (brand_id, name) VALUES (6, 'DBS');
INSERT INTO model (brand_id, name) VALUES (6, 'DBS Superlaggera');
INSERT INTO model (brand_id, name) VALUES (6, 'DBX');
INSERT INTO model (brand_id, name) VALUES (6, 'Lagonda');
INSERT INTO model (brand_id, name) VALUES (6, 'One-77');
INSERT INTO model (brand_id, name) VALUES (6, 'Rapide');
INSERT INTO model (brand_id, name) VALUES (6, 'V8');
INSERT INTO model (brand_id, name) VALUES (6, 'V8 Vantage');
INSERT INTO model (brand_id, name) VALUES (6, 'V8 Zagato');
INSERT INTO model (brand_id, name) VALUES (6, 'V12 Vanquish');
INSERT INTO model (brand_id, name) VALUES (6, 'V12 Vantage');
INSERT INTO model (brand_id, name) VALUES (6, 'Vanquish');
INSERT INTO model (brand_id, name) VALUES (6, 'Virage');
INSERT INTO model (brand_id, name) VALUES (6, 'Volatne');
INSERT INTO brand (name) VALUES ('Audi');
INSERT INTO model (brand_id, name) VALUES (7, '80');
INSERT INTO model (brand_id, name) VALUES (7, '90');
INSERT INTO model (brand_id, name) VALUES (7, '100');
INSERT INTO model (brand_id, name) VALUES (7, '200');
INSERT INTO model (brand_id, name) VALUES (7, 'A1');
INSERT INTO model (brand_id, name) VALUES (7, 'A2');
INSERT INTO model (brand_id, name) VALUES (7, 'A3');
INSERT INTO model (brand_id, name) VALUES (7, 'A4');
INSERT INTO model (brand_id, name) VALUES (7, 'A4 Allroad');
INSERT INTO model (brand_id, name) VALUES (7, 'A5');
INSERT INTO model (brand_id, name) VALUES (7, 'A6');
INSERT INTO model (brand_id, name) VALUES (7, 'A6 Allroad');
INSERT INTO model (brand_id, name) VALUES (7, 'A7');
INSERT INTO model (brand_id, name) VALUES (7, 'A8');
INSERT INTO model (brand_id, name) VALUES (7, 'Cabriolet');
INSERT INTO model (brand_id, name) VALUES (7, 'Coupe');
INSERT INTO model (brand_id, name) VALUES (7, 'e-tron');
INSERT INTO model (brand_id, name) VALUES (7, 'Q2');
INSERT INTO model (brand_id, name) VALUES (7, 'Q3');
INSERT INTO model (brand_id, name) VALUES (7, 'Q5');
INSERT INTO model (brand_id, name) VALUES (7, 'Q7');
INSERT INTO model (brand_id, name) VALUES (7, 'Q8');
INSERT INTO model (brand_id, name) VALUES (7, 'Qouattro');
INSERT INTO model (brand_id, name) VALUES (7, 'R8');
INSERT INTO model (brand_id, name) VALUES (7, 'RS2');
INSERT INTO model (brand_id, name) VALUES (7, 'RS3');
INSERT INTO model (brand_id, name) VALUES (7, 'RS4');
INSERT INTO model (brand_id, name) VALUES (7, 'RS5');
INSERT INTO model (brand_id, name) VALUES (7, 'RS6');
INSERT INTO model (brand_id, name) VALUES (7, 'RS7');
INSERT INTO model (brand_id, name) VALUES (7, 'RS Q3');
INSERT INTO model (brand_id, name) VALUES (7, 'RS Q8');
INSERT INTO model (brand_id, name) VALUES (7, 'S1');
INSERT INTO model (brand_id, name) VALUES (7, 'S2');
INSERT INTO model (brand_id, name) VALUES (7, 'S3');
INSERT INTO model (brand_id, name) VALUES (7, 'S4');
INSERT INTO model (brand_id, name) VALUES (7, 'S5');
INSERT INTO model (brand_id, name) VALUES (7, 'S6');
INSERT INTO model (brand_id, name) VALUES (7, 'S7');
INSERT INTO model (brand_id, name) VALUES (7, 'S8');
INSERT INTO model (brand_id, name) VALUES (7, 'SQ2');
INSERT INTO model (brand_id, name) VALUES (7, 'SQ5');
INSERT INTO model (brand_id, name) VALUES (7, 'SQ7');
INSERT INTO model (brand_id, name) VALUES (7, 'SQ8');
INSERT INTO model (brand_id, name) VALUES (7, 'TT');
INSERT INTO model (brand_id, name) VALUES (7, 'TT RS');
INSERT INTO model (brand_id, name) VALUES (7, 'TT S');
INSERT INTO model (brand_id, name) VALUES (7, 'V8');
INSERT INTO brand (name) VALUES ('Bentley');
INSERT INTO model (brand_id, name) VALUES (8, 'Arnage');
INSERT INTO model (brand_id, name) VALUES (8, 'Azure');
INSERT INTO model (brand_id, name) VALUES (8, 'Bentayga');
INSERT INTO model (brand_id, name) VALUES (8, 'Brooklands');
INSERT INTO model (brand_id, name) VALUES (8, 'Continental Flying Spur');
INSERT INTO model (brand_id, name) VALUES (8, 'Continental GT');
INSERT INTO model (brand_id, name) VALUES (8, 'Eight');
INSERT INTO model (brand_id, name) VALUES (8, 'Mulsanne');
INSERT INTO model (brand_id, name) VALUES (8, 'Turbo R');
INSERT INTO model (brand_id, name) VALUES (8, 'Turbo RT');
INSERT INTO model (brand_id, name) VALUES (8, 'Turbo S');
INSERT INTO brand (name) VALUES ('BMW');
INSERT INTO model (brand_id, name) VALUES (9, '1M');
INSERT INTO model (brand_id, name) VALUES (9, '3GT');
INSERT INTO model (brand_id, name) VALUES (9, '5GT');
INSERT INTO model (brand_id, name) VALUES (9, '6GT');
INSERT INTO model (brand_id, name) VALUES (9, 'i3');
INSERT INTO model (brand_id, name) VALUES (9, 'i8');
INSERT INTO model (brand_id, name) VALUES (9, 'M2');
INSERT INTO model (brand_id, name) VALUES (9, 'M3');
INSERT INTO model (brand_id, name) VALUES (9, 'M4');
INSERT INTO model (brand_id, name) VALUES (9, 'M5');
INSERT INTO model (brand_id, name) VALUES (9, 'M6');
INSERT INTO model (brand_id, name) VALUES (9, 'M8');
INSERT INTO model (brand_id, name) VALUES (9, 'Seria 1');
INSERT INTO model (brand_id, name) VALUES (9, 'Seria 2');
INSERT INTO model (brand_id, name) VALUES (9, 'Seria 3');
INSERT INTO model (brand_id, name) VALUES (9, 'Seria 4');
INSERT INTO model (brand_id, name) VALUES (9, 'Seria 5');
INSERT INTO model (brand_id, name) VALUES (9, 'Seria 6');
INSERT INTO model (brand_id, name) VALUES (9, 'Seria 7');
INSERT INTO model (brand_id, name) VALUES (9, 'Seria 8');
INSERT INTO model (brand_id, name) VALUES (9, 'X1');
INSERT INTO model (brand_id, name) VALUES (9, 'X2');
INSERT INTO model (brand_id, name) VALUES (9, 'X3 M');
INSERT INTO model (brand_id, name) VALUES (9, 'X4');
INSERT INTO model (brand_id, name) VALUES (9, 'X5');
INSERT INTO model (brand_id, name) VALUES (9, 'X5 M');
INSERT INTO model (brand_id, name) VALUES (9, 'X6');
INSERT INTO model (brand_id, name) VALUES (9, 'X6 M');
INSERT INTO model (brand_id, name) VALUES (9, 'X7');
INSERT INTO model (brand_id, name) VALUES (9, 'Z1');
INSERT INTO model (brand_id, name) VALUES (9, 'Z3');
INSERT INTO model (brand_id, name) VALUES (9, 'Z4');
INSERT INTO model (brand_id, name) VALUES (9, 'Z4 M');
INSERT INTO model (brand_id, name) VALUES (9, 'Z8');
INSERT INTO brand (name) VALUES ('Buick');
INSERT INTO model (brand_id, name) VALUES (10, 'Centurion');
INSERT INTO model (brand_id, name) VALUES (10, 'Century');
INSERT INTO model (brand_id, name) VALUES (10, 'Electra');
INSERT INTO model (brand_id, name) VALUES (10, 'Enclave');
INSERT INTO model (brand_id, name) VALUES (10, 'Lacrosse');
INSERT INTO model (brand_id, name) VALUES (10, 'LeSabre');
INSERT INTO model (brand_id, name) VALUES (10, 'Lucerne');
INSERT INTO model (brand_id, name) VALUES (10, 'Park Avenue');
INSERT INTO model (brand_id, name) VALUES (10, 'Reatta');
INSERT INTO model (brand_id, name) VALUES (10, 'Regal');
INSERT INTO model (brand_id, name) VALUES (10, 'Randezvous');
INSERT INTO model (brand_id, name) VALUES (10, 'Riviera');
INSERT INTO model (brand_id, name) VALUES (10, 'Roadmaster');
INSERT INTO model (brand_id, name) VALUES (10, 'Roadmaster');
INSERT INTO model (brand_id, name) VALUES (10, 'Skyhawk');
INSERT INTO model (brand_id, name) VALUES (10, 'Skylark');
INSERT INTO brand (name) VALUES ('Bugatti');
INSERT INTO model (brand_id, name) VALUES (11, 'Chiron');
INSERT INTO model (brand_id, name) VALUES (11, 'Divo');
INSERT INTO model (brand_id, name) VALUES (11, 'EB 110');
INSERT INTO model (brand_id, name) VALUES (11, 'Veyron');
INSERT INTO brand (name) VALUES ('Cadillac');
INSERT INTO model (brand_id, name) VALUES (12, 'Allante');
INSERT INTO model (brand_id, name) VALUES (12, 'ATS');
INSERT INTO model (brand_id, name) VALUES (12, 'BLS');
INSERT INTO model (brand_id, name) VALUES (12, 'Brougham');
INSERT INTO model (brand_id, name) VALUES (12, 'Catera');
INSERT INTO model (brand_id, name) VALUES (12, 'Cimarron');
INSERT INTO model (brand_id, name) VALUES (12, 'CT6');
INSERT INTO model (brand_id, name) VALUES (12, 'CTS');
INSERT INTO model (brand_id, name) VALUES (12, 'Deville');
INSERT INTO model (brand_id, name) VALUES (12, 'DTS');
INSERT INTO model (brand_id, name) VALUES (12, 'Eldorado');
INSERT INTO model (brand_id, name) VALUES (12, 'ELR');
INSERT INTO model (brand_id, name) VALUES (12, 'Escalade');
INSERT INTO model (brand_id, name) VALUES (12, 'Fleetwood');
INSERT INTO model (brand_id, name) VALUES (12, 'Seville');
INSERT INTO model (brand_id, name) VALUES (12, 'SLS');
INSERT INTO model (brand_id, name) VALUES (12, 'SRX');
INSERT INTO model (brand_id, name) VALUES (12, 'STS');
INSERT INTO model (brand_id, name) VALUES (12, 'STS-V');
INSERT INTO model (brand_id, name) VALUES (12, 'XLR');
INSERT INTO model (brand_id, name) VALUES (12, 'XLR-V');
INSERT INTO model (brand_id, name) VALUES (12, 'XT5');
INSERT INTO model (brand_id, name) VALUES (12, 'XTS');
INSERT INTO brand (name) VALUES ('Chevrolet');
INSERT INTO model (brand_id, name) VALUES (13, '1500');
INSERT INTO model (brand_id, name) VALUES (13, '2500');
INSERT INTO model (brand_id, name) VALUES (13, '3500');
INSERT INTO model (brand_id, name) VALUES (13, 'Alero');
INSERT INTO model (brand_id, name) VALUES (13, 'Apache');
INSERT INTO model (brand_id, name) VALUES (13, 'Astro');
INSERT INTO model (brand_id, name) VALUES (13, 'Avalanche');
INSERT INTO model (brand_id, name) VALUES (13, 'Aveo');
INSERT INTO model (brand_id, name) VALUES (13, 'Bel Air');
INSERT INTO model (brand_id, name) VALUES (13, 'Beretta');
INSERT INTO model (brand_id, name) VALUES (13, 'Blazer');
INSERT INTO model (brand_id, name) VALUES (13, 'Bolt');
INSERT INTO model (brand_id, name) VALUES (13, 'C-10');
INSERT INTO model (brand_id, name) VALUES (13, 'C-20');
INSERT INTO model (brand_id, name) VALUES (13, 'C-30');
INSERT INTO model (brand_id, name) VALUES (13, 'Camaro');
INSERT INTO model (brand_id, name) VALUES (13, 'Caprice');
INSERT INTO model (brand_id, name) VALUES (13, 'Captiva');
INSERT INTO model (brand_id, name) VALUES (13, 'Cavalier');
INSERT INTO model (brand_id, name) VALUES (13, 'Celebrity');
INSERT INTO model (brand_id, name) VALUES (13, 'Chevelle');
INSERT INTO model (brand_id, name) VALUES (13, 'Chevy Van');
INSERT INTO model (brand_id, name) VALUES (13, 'Citation');
INSERT INTO model (brand_id, name) VALUES (13, 'Cobalt');
INSERT INTO model (brand_id, name) VALUES (13, 'Colorado');
INSERT INTO model (brand_id, name) VALUES (13, 'Corsica');
INSERT INTO model (brand_id, name) VALUES (13, 'Corvette');
INSERT INTO model (brand_id, name) VALUES (13, 'Cruze');
INSERT INTO model (brand_id, name) VALUES (13, 'El Camino');
INSERT INTO model (brand_id, name) VALUES (13, 'Epica');
INSERT INTO model (brand_id, name) VALUES (13, 'Equinox');
INSERT INTO model (brand_id, name) VALUES (13, 'Evanda');
INSERT INTO model (brand_id, name) VALUES (13, 'Express');
INSERT INTO model (brand_id, name) VALUES (13, 'G');
INSERT INTO model (brand_id, name) VALUES (13, 'HHR');
INSERT INTO model (brand_id, name) VALUES (13, 'Impala');
INSERT INTO model (brand_id, name) VALUES (13, 'K30');
INSERT INTO model (brand_id, name) VALUES (13, 'K1500');
INSERT INTO model (brand_id, name) VALUES (13, 'Kalos');
INSERT INTO model (brand_id, name) VALUES (13, 'Lacetti');
INSERT INTO model (brand_id, name) VALUES (13, 'Lumina');
INSERT INTO model (brand_id, name) VALUES (13, 'Malibu');
INSERT INTO model (brand_id, name) VALUES (13, 'Matiz');
INSERT INTO model (brand_id, name) VALUES (13, 'Monte Carlo');
INSERT INTO model (brand_id, name) VALUES (13, 'Monza');
INSERT INTO model (brand_id, name) VALUES (13, 'Nova');
INSERT INTO model (brand_id, name) VALUES (13, 'Nubira');
INSERT INTO model (brand_id, name) VALUES (13, 'Orlando');
INSERT INTO model (brand_id, name) VALUES (13, 'Rezzo');
INSERT INTO model (brand_id, name) VALUES (13, 'S-10');
INSERT INTO model (brand_id, name) VALUES (13, 'Silverado');
INSERT INTO model (brand_id, name) VALUES (13, 'Spark');
INSERT INTO model (brand_id, name) VALUES (13, 'Spectrum');
INSERT INTO model (brand_id, name) VALUES (13, 'SSR');
INSERT INTO model (brand_id, name) VALUES (13, 'Suburban');
INSERT INTO model (brand_id, name) VALUES (13, 'Tacuma');
INSERT INTO model (brand_id, name) VALUES (13, 'Tahoe');
INSERT INTO model (brand_id, name) VALUES (13, 'Trailblazer');
INSERT INTO model (brand_id, name) VALUES (13, 'Trans Sport');
INSERT INTO model (brand_id, name) VALUES (13, 'Traverse');
INSERT INTO model (brand_id, name) VALUES (13, 'Trax');
INSERT INTO model (brand_id, name) VALUES (13, 'Venture');
INSERT INTO model (brand_id, name) VALUES (13, 'Volt');
INSERT INTO brand (name) VALUES ('Chrysler');
INSERT INTO model (brand_id, name) VALUES (14, '200');
INSERT INTO model (brand_id, name) VALUES (14, '300');
INSERT INTO model (brand_id, name) VALUES (14, '300C');
INSERT INTO model (brand_id, name) VALUES (14, '300M');
INSERT INTO model (brand_id, name) VALUES (14, '300s');
INSERT INTO model (brand_id, name) VALUES (14, 'Aspen');
INSERT INTO model (brand_id, name) VALUES (14, 'Caravan');
INSERT INTO model (brand_id, name) VALUES (14, 'Concorde');
INSERT INTO model (brand_id, name) VALUES (14, 'Crossfire');
INSERT INTO model (brand_id, name) VALUES (14, 'Daytona');
INSERT INTO model (brand_id, name) VALUES (14, 'ES');
INSERT INTO model (brand_id, name) VALUES (14, 'Grant Voyager');
INSERT INTO model (brand_id, name) VALUES (14, 'GS');
INSERT INTO model (brand_id, name) VALUES (14, 'GTS');
INSERT INTO model (brand_id, name) VALUES (14, 'Le Baron');
INSERT INTO model (brand_id, name) VALUES (14, 'LHS');
INSERT INTO model (brand_id, name) VALUES (14, 'Neon');
INSERT INTO model (brand_id, name) VALUES (14, 'New Yorker');
INSERT INTO model (brand_id, name) VALUES (14, 'Pacifica');
INSERT INTO model (brand_id, name) VALUES (14, 'Prowler');
INSERT INTO model (brand_id, name) VALUES (14, 'PT Cruiser');
INSERT INTO model (brand_id, name) VALUES (14, 'Saratoga');
INSERT INTO model (brand_id, name) VALUES (14, 'Sebring');
INSERT INTO model (brand_id, name) VALUES (14, 'Stratus');
INSERT INTO model (brand_id, name) VALUES (14, 'Town & Country');
INSERT INTO model (brand_id, name) VALUES (14, 'Valiant');
INSERT INTO model (brand_id, name) VALUES (14, 'Viper');
INSERT INTO model (brand_id, name) VALUES (14, 'Vision');
INSERT INTO model (brand_id, name) VALUES (14, 'Voyager');
INSERT INTO brand (name) VALUES ('Citroen');
INSERT INTO model (brand_id, name) VALUES (15, '2 CV');
INSERT INTO model (brand_id, name) VALUES (15, 'AX');
INSERT INTO model (brand_id, name) VALUES (15, 'Axel');
INSERT INTO model (brand_id, name) VALUES (15, 'Berlingo');
INSERT INTO model (brand_id, name) VALUES (15, 'BX');
INSERT INTO model (brand_id, name) VALUES (15, 'C-Crosser');
INSERT INTO model (brand_id, name) VALUES (15, 'C-Elysee');
INSERT INTO model (brand_id, name) VALUES (15, 'C1');
INSERT INTO model (brand_id, name) VALUES (15, 'C2');
INSERT INTO model (brand_id, name) VALUES (15, 'C3');
INSERT INTO model (brand_id, name) VALUES (15, 'C3 Aircross');
INSERT INTO model (brand_id, name) VALUES (15, 'C3 Picasso');
INSERT INTO model (brand_id, name) VALUES (15, 'C3 Pluriel');
INSERT INTO model (brand_id, name) VALUES (15, 'C4');
INSERT INTO model (brand_id, name) VALUES (15, 'C4 Aircross');
INSERT INTO model (brand_id, name) VALUES (15, 'C4 Cactus');
INSERT INTO model (brand_id, name) VALUES (15, 'C4 Grand Picasso');
INSERT INTO model (brand_id, name) VALUES (15, 'C4 Picasso');
INSERT INTO model (brand_id, name) VALUES (15, 'C5');
INSERT INTO model (brand_id, name) VALUES (15, 'C5 Aircross');
INSERT INTO model (brand_id, name) VALUES (15, 'C6');
INSERT INTO model (brand_id, name) VALUES (15, 'C8');
INSERT INTO model (brand_id, name) VALUES (15, 'Evasion');
INSERT INTO model (brand_id, name) VALUES (15, 'GSA');
INSERT INTO model (brand_id, name) VALUES (15, 'Jumper');
INSERT INTO model (brand_id, name) VALUES (15, 'Jumper Combi');
INSERT INTO model (brand_id, name) VALUES (15, 'Nemo');
INSERT INTO model (brand_id, name) VALUES (15, 'Saxo');
INSERT INTO model (brand_id, name) VALUES (15, 'SM');
INSERT INTO model (brand_id, name) VALUES (15, 'SpaceTourer');
INSERT INTO model (brand_id, name) VALUES (15, 'Visa');
INSERT INTO model (brand_id, name) VALUES (15, 'Xantia');
INSERT INTO model (brand_id, name) VALUES (15, 'XM');
INSERT INTO model (brand_id, name) VALUES (15, 'Xsara');
INSERT INTO model (brand_id, name) VALUES (15, 'Xsara Picasso');
INSERT INTO model (brand_id, name) VALUES (15, 'ZX');
INSERT INTO brand (name) VALUES ('Cupra');
INSERT INTO model (brand_id, name) VALUES (16, 'Ateca');
INSERT INTO model (brand_id, name) VALUES (16, 'Formentor');
INSERT INTO model (brand_id, name) VALUES (16, 'Leon');
INSERT INTO model (brand_id, name) VALUES (16, 'Leon Sportstourer');
INSERT INTO brand (name) VALUES ('Dacia');
INSERT INTO model (brand_id, name) VALUES (17, '1300');
INSERT INTO model (brand_id, name) VALUES (17, '1310');
INSERT INTO model (brand_id, name) VALUES (17, '1400');
INSERT INTO model (brand_id, name) VALUES (17, '1410');
INSERT INTO model (brand_id, name) VALUES (17, 'Dokker');
INSERT INTO model (brand_id, name) VALUES (17, 'Dokker Van');
INSERT INTO model (brand_id, name) VALUES (17, 'Duster');
INSERT INTO model (brand_id, name) VALUES (17, 'Lodgy');
INSERT INTO model (brand_id, name) VALUES (17, 'Logan');
INSERT INTO model (brand_id, name) VALUES (17, 'Logan Van');
INSERT INTO model (brand_id, name) VALUES (17, 'Nova');
INSERT INTO model (brand_id, name) VALUES (17, 'Pick Up');
INSERT INTO model (brand_id, name) VALUES (17, 'Sandero');
INSERT INTO model (brand_id, name) VALUES (17, 'Sandero Stepway');
INSERT INTO model (brand_id, name) VALUES (17, 'Solenza');
INSERT INTO model (brand_id, name) VALUES (17, 'Super Nova');
INSERT INTO brand (name) VALUES ('Daewoo');
INSERT INTO model (brand_id, name) VALUES (18, 'Chairman');
INSERT INTO model (brand_id, name) VALUES (18, 'Cielo');
INSERT INTO model (brand_id, name) VALUES (18, 'Espero');
INSERT INTO model (brand_id, name) VALUES (18, 'Evanda');
INSERT INTO model (brand_id, name) VALUES (18, 'Kalos');
INSERT INTO model (brand_id, name) VALUES (18, 'Korando');
INSERT INTO model (brand_id, name) VALUES (18, 'Lacetti');
INSERT INTO model (brand_id, name) VALUES (18, 'Lanos');
INSERT INTO model (brand_id, name) VALUES (18, 'Leganza');
INSERT INTO model (brand_id, name) VALUES (18, 'Matiz');
INSERT INTO model (brand_id, name) VALUES (18, 'Musso');
INSERT INTO model (brand_id, name) VALUES (18, 'Nexia');
INSERT INTO model (brand_id, name) VALUES (18, 'Nubira');
INSERT INTO model (brand_id, name) VALUES (18, 'Racer');
INSERT INTO model (brand_id, name) VALUES (18, 'Rezzo');
INSERT INTO model (brand_id, name) VALUES (18, 'Tacuma');
INSERT INTO model (brand_id, name) VALUES (18, 'Tico');
INSERT INTO brand (name) VALUES ('Daihatsu');
INSERT INTO model (brand_id, name) VALUES (19, 'Applause');
INSERT INTO model (brand_id, name) VALUES (19, 'Charade');
INSERT INTO model (brand_id, name) VALUES (19, 'Charmant');
INSERT INTO model (brand_id, name) VALUES (19, 'Copen');
INSERT INTO model (brand_id, name) VALUES (19, 'Cuore');
INSERT INTO model (brand_id, name) VALUES (19, 'Feroza');
INSERT INTO model (brand_id, name) VALUES (19, 'Fourtrak');
INSERT INTO model (brand_id, name) VALUES (19, 'Freeclimber');
INSERT INTO model (brand_id, name) VALUES (19, 'Gran Move');
INSERT INTO model (brand_id, name) VALUES (19, 'Hijet');
INSERT INTO model (brand_id, name) VALUES (19, 'Materia');
INSERT INTO model (brand_id, name) VALUES (19, 'Move');
INSERT INTO model (brand_id, name) VALUES (19, 'Rocky');
INSERT INTO model (brand_id, name) VALUES (19, 'Sirion');
INSERT INTO model (brand_id, name) VALUES (19, 'Sportrak');
INSERT INTO model (brand_id, name) VALUES (19, 'Terios');
INSERT INTO model (brand_id, name) VALUES (19, 'Trevis');
INSERT INTO model (brand_id, name) VALUES (19, 'YRV');
INSERT INTO brand (name) VALUES ('Dodge');
INSERT INTO model (brand_id, name) VALUES (20, 'Avenger');
INSERT INTO model (brand_id, name) VALUES (20, 'Caliber');
INSERT INTO model (brand_id, name) VALUES (20, 'Caravan');
INSERT INTO model (brand_id, name) VALUES (20, 'Challenger');
INSERT INTO model (brand_id, name) VALUES (20, 'Charger');
INSERT INTO model (brand_id, name) VALUES (20, 'Dakota');
INSERT INTO model (brand_id, name) VALUES (20, 'Dart');
INSERT INTO model (brand_id, name) VALUES (20, 'Daytona');
INSERT INTO model (brand_id, name) VALUES (20, 'Diplomat');
INSERT INTO model (brand_id, name) VALUES (20, 'Durango');
INSERT INTO model (brand_id, name) VALUES (20, 'Dynasty');
INSERT INTO model (brand_id, name) VALUES (20, 'Gran Caravan');
INSERT INTO model (brand_id, name) VALUES (20, 'Hornet');
INSERT INTO model (brand_id, name) VALUES (20, 'Intrepid');
INSERT INTO model (brand_id, name) VALUES (20, 'Journey');
INSERT INTO model (brand_id, name) VALUES (20, 'Magnum');
INSERT INTO model (brand_id, name) VALUES (20, 'Monaco');
INSERT INTO model (brand_id, name) VALUES (20, 'Neon');
INSERT INTO model (brand_id, name) VALUES (20, 'Nitro');
INSERT INTO model (brand_id, name) VALUES (20, 'Omni');
INSERT INTO model (brand_id, name) VALUES (20, 'RAM');
INSERT INTO model (brand_id, name) VALUES (20, 'Spirit');
INSERT INTO model (brand_id, name) VALUES (20, 'Stealth');
INSERT INTO model (brand_id, name) VALUES (20, 'Stratus');
INSERT INTO model (brand_id, name) VALUES (20, 'Viper');
INSERT INTO brand (name) VALUES ('DS Automobiles');
INSERT INTO model (brand_id, name) VALUES (21, 'DS');
INSERT INTO model (brand_id, name) VALUES (21, 'DS 3');
INSERT INTO model (brand_id, name) VALUES (21, 'DS 3 Crossback');
INSERT INTO model (brand_id, name) VALUES (21, 'DS 4');
INSERT INTO model (brand_id, name) VALUES (21, 'DS 4 Crossback');
INSERT INTO model (brand_id, name) VALUES (21, 'DS 5');
INSERT INTO model (brand_id, name) VALUES (21, 'DS 7 Crossback');
INSERT INTO brand (name) VALUES ('Ferrari');
INSERT INTO model (brand_id, name) VALUES (22, '208');
INSERT INTO model (brand_id, name) VALUES (22, '248');
INSERT INTO model (brand_id, name) VALUES (22, '250');
INSERT INTO model (brand_id, name) VALUES (22, '288');
INSERT INTO model (brand_id, name) VALUES (22, '308');
INSERT INTO model (brand_id, name) VALUES (22, '328');
INSERT INTO model (brand_id, name) VALUES (22, '330');
INSERT INTO model (brand_id, name) VALUES (22, '348');
INSERT INTO model (brand_id, name) VALUES (22, '360');
INSERT INTO model (brand_id, name) VALUES (22, '365');
INSERT INTO model (brand_id, name) VALUES (22, '400');
INSERT INTO model (brand_id, name) VALUES (22, '412');
INSERT INTO model (brand_id, name) VALUES (22, '456');
INSERT INTO model (brand_id, name) VALUES (22, '458 Italia');
INSERT INTO model (brand_id, name) VALUES (22, '488');
INSERT INTO model (brand_id, name) VALUES (22, '512');
INSERT INTO model (brand_id, name) VALUES (22, '575');
INSERT INTO model (brand_id, name) VALUES (22, '599GTB');
INSERT INTO model (brand_id, name) VALUES (22, '612');
INSERT INTO model (brand_id, name) VALUES (22, '750');
INSERT INTO model (brand_id, name) VALUES (22, '812 Superfast');
INSERT INTO model (brand_id, name) VALUES (22, 'California');
INSERT INTO model (brand_id, name) VALUES (22, 'Daytona');
INSERT INTO model (brand_id, name) VALUES (22, 'Dino GT4');
INSERT INTO model (brand_id, name) VALUES (22, 'Enzo');
INSERT INTO model (brand_id, name) VALUES (22, 'F12barlinetta');
INSERT INTO model (brand_id, name) VALUES (22, 'F40');
INSERT INTO model (brand_id, name) VALUES (22, 'F50');
INSERT INTO model (brand_id, name) VALUES (22, 'F355');
INSERT INTO model (brand_id, name) VALUES (22, 'F360');
INSERT INTO model (brand_id, name) VALUES (22, 'F430');
INSERT INTO model (brand_id, name) VALUES (22, 'F550');
INSERT INTO model (brand_id, name) VALUES (22, 'FF');
INSERT INTO model (brand_id, name) VALUES (22, 'GTC4Lusso');
INSERT INTO model (brand_id, name) VALUES (22, 'LaFerrari');
INSERT INTO model (brand_id, name) VALUES (22, 'Mondial');
INSERT INTO model (brand_id, name) VALUES (22, 'Portofino');
INSERT INTO model (brand_id, name) VALUES (22, 'Superamerica');
INSERT INTO model (brand_id, name) VALUES (22, 'Testarossa');
INSERT INTO brand (name) VALUES ('Fiat');
INSERT INTO model (brand_id, name) VALUES (23, '124');
INSERT INTO model (brand_id, name) VALUES (23, '124 Spider');
INSERT INTO model (brand_id, name) VALUES (23, '125p');
INSERT INTO model (brand_id, name) VALUES (23, '126');
INSERT INTO model (brand_id, name) VALUES (23, '127');
INSERT INTO model (brand_id, name) VALUES (23, '128');
INSERT INTO model (brand_id, name) VALUES (23, '130');
INSERT INTO model (brand_id, name) VALUES (23, '131');
INSERT INTO model (brand_id, name) VALUES (23, '132');
INSERT INTO model (brand_id, name) VALUES (23, '500');
INSERT INTO model (brand_id, name) VALUES (23, '500L');
INSERT INTO model (brand_id, name) VALUES (23, '500X');
INSERT INTO model (brand_id, name) VALUES (23, '600');
INSERT INTO model (brand_id, name) VALUES (23, '850');
INSERT INTO model (brand_id, name) VALUES (23, 'Albea');
INSERT INTO model (brand_id, name) VALUES (23, 'Barchetta');
INSERT INTO model (brand_id, name) VALUES (23, 'Brava');
INSERT INTO model (brand_id, name) VALUES (23, 'Bravo');
INSERT INTO model (brand_id, name) VALUES (23, 'Cinquecento');
INSERT INTO model (brand_id, name) VALUES (23, 'Coupe');
INSERT INTO model (brand_id, name) VALUES (23, 'Croma');
INSERT INTO model (brand_id, name) VALUES (23, 'Dino');
INSERT INTO model (brand_id, name) VALUES (23, 'Doblo');
INSERT INTO model (brand_id, name) VALUES (23, 'Ducato');
INSERT INTO model (brand_id, name) VALUES (23, 'Fiorino');
INSERT INTO model (brand_id, name) VALUES (23, 'Freemont');
INSERT INTO model (brand_id, name) VALUES (23, 'Fullback');
INSERT INTO model (brand_id, name) VALUES (23, 'Grande Punto');
INSERT INTO model (brand_id, name) VALUES (23, 'Idea');
INSERT INTO model (brand_id, name) VALUES (23, 'Linea');
INSERT INTO model (brand_id, name) VALUES (23, 'Marea');
INSERT INTO model (brand_id, name) VALUES (23, 'Multipla');
INSERT INTO model (brand_id, name) VALUES (23, 'Palio');
INSERT INTO model (brand_id, name) VALUES (23, 'Panda');
INSERT INTO model (brand_id, name) VALUES (23, 'Punto');
INSERT INTO model (brand_id, name) VALUES (23, 'Punto 2012');
INSERT INTO model (brand_id, name) VALUES (23, 'Punto Evo');
INSERT INTO model (brand_id, name) VALUES (23, 'Qubo');
INSERT INTO model (brand_id, name) VALUES (23, 'Regata');
INSERT INTO model (brand_id, name) VALUES (23, 'Ritmo');
INSERT INTO model (brand_id, name) VALUES (23, 'Scudo');
INSERT INTO model (brand_id, name) VALUES (23, 'Sedici');
INSERT INTO model (brand_id, name) VALUES (23, 'Seicento');
INSERT INTO model (brand_id, name) VALUES (23, 'Siena');
INSERT INTO model (brand_id, name) VALUES (23, 'Spider Europa');
INSERT INTO model (brand_id, name) VALUES (23, 'Stilo');
INSERT INTO model (brand_id, name) VALUES (23, 'Strada');
INSERT INTO model (brand_id, name) VALUES (23, 'Talento');
INSERT INTO model (brand_id, name) VALUES (23, 'Tempra');
INSERT INTO model (brand_id, name) VALUES (23, 'Tipo');
INSERT INTO model (brand_id, name) VALUES (23, 'Ulysse');
INSERT INTO model (brand_id, name) VALUES (23, 'Uno');
INSERT INTO model (brand_id, name) VALUES (23, 'X 1');
INSERT INTO brand (name) VALUES ('Ford');
INSERT INTO model (brand_id, name) VALUES (24, 'Aerostar');
INSERT INTO model (brand_id, name) VALUES (24, 'Aspire');
INSERT INTO model (brand_id, name) VALUES (24, 'B-MAX');
INSERT INTO model (brand_id, name) VALUES (24, 'Bronco');
INSERT INTO model (brand_id, name) VALUES (24, 'C-MAX');
INSERT INTO model (brand_id, name) VALUES (24, 'Capri');
INSERT INTO model (brand_id, name) VALUES (24, 'Contour');
INSERT INTO model (brand_id, name) VALUES (24, 'Cougar');
INSERT INTO model (brand_id, name) VALUES (24, 'Courier');
INSERT INTO model (brand_id, name) VALUES (24, 'Crown');
INSERT INTO model (brand_id, name) VALUES (24, 'Ecoline');
INSERT INTO model (brand_id, name) VALUES (24, 'EcoSport');
INSERT INTO model (brand_id, name) VALUES (24, 'EDGE');
INSERT INTO model (brand_id, name) VALUES (24, 'Escape');
INSERT INTO model (brand_id, name) VALUES (24, 'Escort');
INSERT INTO model (brand_id, name) VALUES (24, 'Excursion');
INSERT INTO model (brand_id, name) VALUES (24, 'Expedition');
INSERT INTO model (brand_id, name) VALUES (24, 'Explorer');
INSERT INTO model (brand_id, name) VALUES (24, 'F150');
INSERT INTO model (brand_id, name) VALUES (24, 'F250');
INSERT INTO model (brand_id, name) VALUES (24, 'F350');
INSERT INTO model (brand_id, name) VALUES (24, 'Fairlane');
INSERT INTO model (brand_id, name) VALUES (24, 'Falcon');
INSERT INTO model (brand_id, name) VALUES (24, 'Festiva');
INSERT INTO model (brand_id, name) VALUES (24, 'Fiesta');
INSERT INTO model (brand_id, name) VALUES (24, 'FIVE HUNDRED');
INSERT INTO model (brand_id, name) VALUES (24, 'Focus');
INSERT INTO model (brand_id, name) VALUES (24, 'Focus C-Max');
INSERT INTO model (brand_id, name) VALUES (24, 'Freestar');
INSERT INTO model (brand_id, name) VALUES (24, 'Freestyle');
INSERT INTO model (brand_id, name) VALUES (24, 'Fusion');
INSERT INTO model (brand_id, name) VALUES (24, 'Galaxy');
INSERT INTO model (brand_id, name) VALUES (24, 'Granada');
INSERT INTO model (brand_id, name) VALUES (24, 'Grand C-MAX');
INSERT INTO model (brand_id, name) VALUES (24, 'GT');
INSERT INTO model (brand_id, name) VALUES (24, 'KA');
INSERT INTO model (brand_id, name) VALUES (24, 'Kuga');
INSERT INTO model (brand_id, name) VALUES (24, 'Maveric');
INSERT INTO model (brand_id, name) VALUES (24, 'Mercury');
INSERT INTO model (brand_id, name) VALUES (24, 'Mondeo');
INSERT INTO model (brand_id, name) VALUES (24, 'Mustang');
INSERT INTO model (brand_id, name) VALUES (24, 'Orion');
INSERT INTO model (brand_id, name) VALUES (24, 'Probe');
INSERT INTO model (brand_id, name) VALUES (24, 'Puma');
INSERT INTO model (brand_id, name) VALUES (24, 'Ranchero');
INSERT INTO model (brand_id, name) VALUES (24, 'Ranger');
INSERT INTO model (brand_id, name) VALUES (24, 'Ranger Raptor');
INSERT INTO model (brand_id, name) VALUES (24, 'S-Max');
INSERT INTO model (brand_id, name) VALUES (24, 'Scorpio');
INSERT INTO model (brand_id, name) VALUES (24, 'Sierra');
INSERT INTO model (brand_id, name) VALUES (24, 'Streetka');
INSERT INTO model (brand_id, name) VALUES (24, 'Taunus');
INSERT INTO model (brand_id, name) VALUES (24, 'Taurus');
INSERT INTO model (brand_id, name) VALUES (24, 'Tempo');
INSERT INTO model (brand_id, name) VALUES (24, 'Thunderbird');
INSERT INTO model (brand_id, name) VALUES (24, 'Tourneo Connect');
INSERT INTO model (brand_id, name) VALUES (24, 'Tourneo Courier');
INSERT INTO model (brand_id, name) VALUES (24, 'Tourneo Custom');
INSERT INTO model (brand_id, name) VALUES (24, 'Transit');
INSERT INTO model (brand_id, name) VALUES (24, 'Transit Connect');
INSERT INTO model (brand_id, name) VALUES (24, 'Transit Courier');
INSERT INTO model (brand_id, name) VALUES (24, 'Transit Custom');
INSERT INTO model (brand_id, name) VALUES (24, 'Transit Custom');
INSERT INTO model (brand_id, name) VALUES (24, 'Windstar');
INSERT INTO brand (name) VALUES ('Honda');
INSERT INTO model (brand_id, name) VALUES (25, 'Accord');
INSERT INTO model (brand_id, name) VALUES (25, 'Aerodeck');
INSERT INTO model (brand_id, name) VALUES (25, 'City');
INSERT INTO model (brand_id, name) VALUES (25, 'Civic');
INSERT INTO model (brand_id, name) VALUES (25, 'Concerto');
INSERT INTO model (brand_id, name) VALUES (25, 'CR-V');
INSERT INTO model (brand_id, name) VALUES (25, 'CR-Z');
INSERT INTO model (brand_id, name) VALUES (25, 'CRX');
INSERT INTO model (brand_id, name) VALUES (25, 'Element');
INSERT INTO model (brand_id, name) VALUES (25, 'FR-V');
INSERT INTO model (brand_id, name) VALUES (25, 'HR-V');
INSERT INTO model (brand_id, name) VALUES (25, 'Insight');
INSERT INTO model (brand_id, name) VALUES (25, 'Integra');
INSERT INTO model (brand_id, name) VALUES (25, 'Jazz');
INSERT INTO model (brand_id, name) VALUES (25, 'Legend');
INSERT INTO model (brand_id, name) VALUES (25, 'Logo');
INSERT INTO model (brand_id, name) VALUES (25, 'NSX');
INSERT INTO model (brand_id, name) VALUES (25, 'Odyssey');
INSERT INTO model (brand_id, name) VALUES (25, 'Pilot');
INSERT INTO model (brand_id, name) VALUES (25, 'Prelude');
INSERT INTO model (brand_id, name) VALUES (25, 'Ridgeline');
INSERT INTO model (brand_id, name) VALUES (25, 'S 2000');
INSERT INTO model (brand_id, name) VALUES (25, 'Shuttle');
INSERT INTO model (brand_id, name) VALUES (25, 'Stream');
INSERT INTO brand (name) VALUES ('Hummer');
INSERT INTO model (brand_id, name) VALUES (26, 'H1');
INSERT INTO model (brand_id, name) VALUES (26, 'H2');
INSERT INTO model (brand_id, name) VALUES (26, 'H3');
INSERT INTO brand (name) VALUES ('Hyundai');
INSERT INTO model (brand_id, name) VALUES (27, 'Accent');
INSERT INTO model (brand_id, name) VALUES (27, 'Atos');
INSERT INTO model (brand_id, name) VALUES (27, 'Avante');
INSERT INTO model (brand_id, name) VALUES (27, 'Azera');
INSERT INTO model (brand_id, name) VALUES (27, 'Coupe');
INSERT INTO model (brand_id, name) VALUES (27, 'Elantra');
INSERT INTO model (brand_id, name) VALUES (27, 'Equus');
INSERT INTO model (brand_id, name) VALUES (27, 'Excel');
INSERT INTO model (brand_id, name) VALUES (27, 'Galloper');
INSERT INTO model (brand_id, name) VALUES (27, 'Genesis');
INSERT INTO model (brand_id, name) VALUES (27, 'Genesis Coupe');
INSERT INTO model (brand_id, name) VALUES (27, 'Getz');
INSERT INTO model (brand_id, name) VALUES (27, 'Grandeur');
INSERT INTO model (brand_id, name) VALUES (27, 'Grand Santa Fe');
INSERT INTO model (brand_id, name) VALUES (27, 'H-1');
INSERT INTO model (brand_id, name) VALUES (27, 'H-1 Starex');
INSERT INTO model (brand_id, name) VALUES (27, 'H200');
INSERT INTO model (brand_id, name) VALUES (27, 'H350');
INSERT INTO model (brand_id, name) VALUES (27, 'i10');
INSERT INTO model (brand_id, name) VALUES (27, 'i20');
INSERT INTO model (brand_id, name) VALUES (27, 'i25');
INSERT INTO model (brand_id, name) VALUES (27, 'i30');
INSERT INTO model (brand_id, name) VALUES (27, 'i30 N');
INSERT INTO model (brand_id, name) VALUES (27, 'i40');
INSERT INTO model (brand_id, name) VALUES (27, 'IONIQ');
INSERT INTO model (brand_id, name) VALUES (27, 'ix20');
INSERT INTO model (brand_id, name) VALUES (27, 'ix35');
INSERT INTO model (brand_id, name) VALUES (27, 'ix55');
INSERT INTO model (brand_id, name) VALUES (27, 'Kona');
INSERT INTO model (brand_id, name) VALUES (27, 'Lantra');
INSERT INTO model (brand_id, name) VALUES (27, 'Matrix');
INSERT INTO model (brand_id, name) VALUES (27, 'Pony');
INSERT INTO model (brand_id, name) VALUES (27, 'S-Coupe');
INSERT INTO model (brand_id, name) VALUES (27, 'Santa Fe');
INSERT INTO model (brand_id, name) VALUES (27, 'Santamo');
INSERT INTO model (brand_id, name) VALUES (27, 'Sonata');
INSERT INTO model (brand_id, name) VALUES (27, 'Sonica');
INSERT INTO model (brand_id, name) VALUES (27, 'Terracan');
INSERT INTO model (brand_id, name) VALUES (27, 'Trajet');
INSERT INTO model (brand_id, name) VALUES (27, 'Tucson');
INSERT INTO model (brand_id, name) VALUES (27, 'Veloster');
INSERT INTO model (brand_id, name) VALUES (27, 'Veracruz');
INSERT INTO model (brand_id, name) VALUES (27, 'XG 30');
INSERT INTO model (brand_id, name) VALUES (27, 'XG 300');
INSERT INTO brand (name) VALUES ('Infiniti');
INSERT INTO model (brand_id, name) VALUES (28, 'EX');
INSERT INTO model (brand_id, name) VALUES (28, 'FX');
INSERT INTO model (brand_id, name) VALUES (28, 'G');
INSERT INTO model (brand_id, name) VALUES (28, 'I30');
INSERT INTO model (brand_id, name) VALUES (28, 'I35');
INSERT INTO model (brand_id, name) VALUES (28, 'J30');
INSERT INTO model (brand_id, name) VALUES (28, 'M');
INSERT INTO model (brand_id, name) VALUES (28, 'Q30');
INSERT INTO model (brand_id, name) VALUES (28, 'Q45');
INSERT INTO model (brand_id, name) VALUES (28, 'Q50');
INSERT INTO model (brand_id, name) VALUES (28, 'Q60');
INSERT INTO model (brand_id, name) VALUES (28, 'Q70');
INSERT INTO model (brand_id, name) VALUES (28, 'QX');
INSERT INTO model (brand_id, name) VALUES (28, 'QX30');
INSERT INTO model (brand_id, name) VALUES (28, 'QX50');
INSERT INTO model (brand_id, name) VALUES (28, 'QX60');
INSERT INTO model (brand_id, name) VALUES (28, 'QX70');
INSERT INTO brand (name) VALUES ('Isuzu');
INSERT INTO model (brand_id, name) VALUES (29, 'Campo');
INSERT INTO model (brand_id, name) VALUES (29, 'D-MAX');
INSERT INTO model (brand_id, name) VALUES (29, 'Germini');
INSERT INTO model (brand_id, name) VALUES (29, 'Midi');
INSERT INTO model (brand_id, name) VALUES (29, 'Pick up');
INSERT INTO model (brand_id, name) VALUES (29, 'Trooper');
INSERT INTO brand (name) VALUES ('Jaguar');
INSERT INTO model (brand_id, name) VALUES (30, 'Daimler');
INSERT INTO model (brand_id, name) VALUES (30, 'E-Pace');
INSERT INTO model (brand_id, name) VALUES (30, 'E-Type');
INSERT INTO model (brand_id, name) VALUES (30, 'F-Pace');
INSERT INTO model (brand_id, name) VALUES (30, 'F-Type');
INSERT INTO model (brand_id, name) VALUES (30, 'I-Pace');
INSERT INTO model (brand_id, name) VALUES (30, 'MK II');
INSERT INTO model (brand_id, name) VALUES (30, 'S-Type');
INSERT INTO model (brand_id, name) VALUES (30, 'X-Type');
INSERT INTO model (brand_id, name) VALUES (30, 'XE');
INSERT INTO model (brand_id, name) VALUES (30, 'XF');
INSERT INTO model (brand_id, name) VALUES (30, 'XJ');
INSERT INTO model (brand_id, name) VALUES (30, 'XJS');
INSERT INTO model (brand_id, name) VALUES (30, 'XK');
INSERT INTO model (brand_id, name) VALUES (30, 'XK8');
INSERT INTO brand (name) VALUES ('Jeep');
INSERT INTO model (brand_id, name) VALUES (31, 'Cherokee');
INSERT INTO model (brand_id, name) VALUES (31, 'CJ');
INSERT INTO model (brand_id, name) VALUES (31, 'Comanche');
INSERT INTO model (brand_id, name) VALUES (31, 'Commander');
INSERT INTO model (brand_id, name) VALUES (31, 'Compass');
INSERT INTO model (brand_id, name) VALUES (31, 'Gladiator');
INSERT INTO model (brand_id, name) VALUES (31, 'Grand Cherokee');
INSERT INTO model (brand_id, name) VALUES (31, 'Liberty');
INSERT INTO model (brand_id, name) VALUES (31, 'Patriot');
INSERT INTO model (brand_id, name) VALUES (31, 'Renegade');
INSERT INTO model (brand_id, name) VALUES (31, 'Wagoneer');
INSERT INTO model (brand_id, name) VALUES (31, 'Willys');
INSERT INTO model (brand_id, name) VALUES (31, 'Wrangler');
INSERT INTO brand (name) VALUES ('Kia');
INSERT INTO model (brand_id, name) VALUES (32, 'Asia Rocsta');
INSERT INTO model (brand_id, name) VALUES (32, 'Besta');
INSERT INTO model (brand_id, name) VALUES (32, 'Carens');
INSERT INTO model (brand_id, name) VALUES (32, 'Carnival');
INSERT INTO model (brand_id, name) VALUES (32, 'Ceed');
INSERT INTO model (brand_id, name) VALUES (32, 'Cerato');
INSERT INTO model (brand_id, name) VALUES (32, 'Clarus');
INSERT INTO model (brand_id, name) VALUES (32, 'Elan');
INSERT INTO model (brand_id, name) VALUES (32, 'Joice');
INSERT INTO model (brand_id, name) VALUES (32, 'Leo');
INSERT INTO model (brand_id, name) VALUES (32, 'Magentis');
INSERT INTO model (brand_id, name) VALUES (32, 'Mentor');
INSERT INTO model (brand_id, name) VALUES (32, 'Niro');
INSERT INTO model (brand_id, name) VALUES (32, 'Opirus');
INSERT INTO model (brand_id, name) VALUES (32, 'Optima');
INSERT INTO model (brand_id, name) VALUES (32, 'Picanto');
INSERT INTO model (brand_id, name) VALUES (32, 'Pregio');
INSERT INTO model (brand_id, name) VALUES (32, 'Pride');
INSERT INTO model (brand_id, name) VALUES (32, 'Pro_ceed');
INSERT INTO model (brand_id, name) VALUES (32, 'Retona');
INSERT INTO model (brand_id, name) VALUES (32, 'Rio');
INSERT INTO model (brand_id, name) VALUES (32, 'Roadsterd');
INSERT INTO model (brand_id, name) VALUES (32, 'Rockster');
INSERT INTO model (brand_id, name) VALUES (32, 'Sedona');
INSERT INTO model (brand_id, name) VALUES (32, 'Sephia');
INSERT INTO model (brand_id, name) VALUES (32, 'Shuma');
INSERT INTO model (brand_id, name) VALUES (32, 'Sorento');
INSERT INTO model (brand_id, name) VALUES (32, 'Soul');
INSERT INTO model (brand_id, name) VALUES (32, 'Spectra');
INSERT INTO model (brand_id, name) VALUES (32, 'Sportage');
INSERT INTO model (brand_id, name) VALUES (32, 'Stinger');
INSERT INTO model (brand_id, name) VALUES (32, 'Stonic');
INSERT INTO model (brand_id, name) VALUES (32, 'Venga');
INSERT INTO model (brand_id, name) VALUES (32, 'XCeed');
INSERT INTO brand (name) VALUES ('Lamborghini');
INSERT INTO model (brand_id, name) VALUES (33, 'Aventador');
INSERT INTO model (brand_id, name) VALUES (33, 'Countach');
INSERT INTO model (brand_id, name) VALUES (33, 'Diablo');
INSERT INTO model (brand_id, name) VALUES (33, 'Espada');
INSERT INTO model (brand_id, name) VALUES (33, 'Gallardo');
INSERT INTO model (brand_id, name) VALUES (33, 'Huracan');
INSERT INTO model (brand_id, name) VALUES (33, 'Jalpa');
INSERT INTO model (brand_id, name) VALUES (33, 'LM');
INSERT INTO model (brand_id, name) VALUES (33, 'Miura');
INSERT INTO model (brand_id, name) VALUES (33, 'Murcielago');
INSERT INTO model (brand_id, name) VALUES (33, 'Urraco');
INSERT INTO model (brand_id, name) VALUES (33, 'Urus');
INSERT INTO brand (name) VALUES ('Lancia');
INSERT INTO model (brand_id, name) VALUES (34, 'Beta');
INSERT INTO model (brand_id, name) VALUES (34, 'Dedra');
INSERT INTO model (brand_id, name) VALUES (34, 'Delta');
INSERT INTO model (brand_id, name) VALUES (34, 'Flamina');
INSERT INTO model (brand_id, name) VALUES (34, 'Fulvia');
INSERT INTO model (brand_id, name) VALUES (34, 'Gamma');
INSERT INTO model (brand_id, name) VALUES (34, 'Kappa');
INSERT INTO model (brand_id, name) VALUES (34, 'Lybra');
INSERT INTO model (brand_id, name) VALUES (34, 'Musa');
INSERT INTO model (brand_id, name) VALUES (34, 'Phedra');
INSERT INTO model (brand_id, name) VALUES (34, 'Prisma');
INSERT INTO model (brand_id, name) VALUES (34, 'Stratos');
INSERT INTO model (brand_id, name) VALUES (34, 'Thema');
INSERT INTO model (brand_id, name) VALUES (34, 'Thesis');
INSERT INTO model (brand_id, name) VALUES (34, 'Voyager');
INSERT INTO brand (name) VALUES ('Land Rover');
INSERT INTO model (brand_id, name) VALUES (35, 'Defender');
INSERT INTO model (brand_id, name) VALUES (35, 'Discovery');
INSERT INTO model (brand_id, name) VALUES (35, 'Discovery Sport');
INSERT INTO model (brand_id, name) VALUES (35, 'Freelander');
INSERT INTO model (brand_id, name) VALUES (35, 'Range Rover');
INSERT INTO model (brand_id, name) VALUES (35, 'Range Rover Evoque');
INSERT INTO model (brand_id, name) VALUES (35, 'Range Rover Sport');
INSERT INTO model (brand_id, name) VALUES (35, 'Range Rover Velar');
INSERT INTO brand (name) VALUES ('Lexus');
INSERT INTO model (brand_id, name) VALUES (36, 'CT');
INSERT INTO model (brand_id, name) VALUES (36, 'ES');
INSERT INTO model (brand_id, name) VALUES (36, 'GS');
INSERT INTO model (brand_id, name) VALUES (36, 'GX');
INSERT INTO model (brand_id, name) VALUES (36, 'HS 250h');
INSERT INTO model (brand_id, name) VALUES (36, 'IS');
INSERT INTO model (brand_id, name) VALUES (36, 'LC');
INSERT INTO model (brand_id, name) VALUES (36, 'LFA');
INSERT INTO model (brand_id, name) VALUES (36, 'LS');
INSERT INTO model (brand_id, name) VALUES (36, 'LX');
INSERT INTO model (brand_id, name) VALUES (36, 'NX');
INSERT INTO model (brand_id, name) VALUES (36, 'RC');
INSERT INTO model (brand_id, name) VALUES (36, 'RX');
INSERT INTO model (brand_id, name) VALUES (36, 'SC');
INSERT INTO model (brand_id, name) VALUES (36, 'UX');
INSERT INTO brand (name) VALUES ('Ligier');
INSERT INTO model (brand_id, name) VALUES (37, 'Altul');
INSERT INTO model (brand_id, name) VALUES (37, 'Ambra');
INSERT INTO model (brand_id, name) VALUES (37, 'Be-Two');
INSERT INTO model (brand_id, name) VALUES (37, 'Be-Up');
INSERT INTO model (brand_id, name) VALUES (37, 'IXO');
INSERT INTO model (brand_id, name) VALUES (37, 'JS49');
INSERT INTO model (brand_id, name) VALUES (37, 'JS50');
INSERT INTO model (brand_id, name) VALUES (37, 'JS50L');
INSERT INTO model (brand_id, name) VALUES (37, 'JS RC');
INSERT INTO model (brand_id, name) VALUES (37, 'Nova');
INSERT INTO model (brand_id, name) VALUES (37, 'Optima');
INSERT INTO model (brand_id, name) VALUES (37, 'X-Too');
INSERT INTO model (brand_id, name) VALUES (37, 'X-Too Max');
INSERT INTO model (brand_id, name) VALUES (37, 'X-Too R');
INSERT INTO model (brand_id, name) VALUES (37, 'X-Too RS');
INSERT INTO brand (name) VALUES ('Lincoln');
INSERT INTO model (brand_id, name) VALUES (38, 'Aviator');
INSERT INTO model (brand_id, name) VALUES (38, 'Continental');
INSERT INTO model (brand_id, name) VALUES (38, 'LS');
INSERT INTO model (brand_id, name) VALUES (38, 'Mark');
INSERT INTO model (brand_id, name) VALUES (38, 'Mark LT');
INSERT INTO model (brand_id, name) VALUES (38, 'MKX');
INSERT INTO model (brand_id, name) VALUES (38, 'MKZ');
INSERT INTO model (brand_id, name) VALUES (38, 'Navigator');
INSERT INTO model (brand_id, name) VALUES (38, 'Town Car');
INSERT INTO brand (name) VALUES ('Łada');
INSERT INTO model (brand_id, name) VALUES (39, '110');
INSERT INTO model (brand_id, name) VALUES (39, '111');
INSERT INTO model (brand_id, name) VALUES (39, '112');
INSERT INTO model (brand_id, name) VALUES (39, '1117');
INSERT INTO model (brand_id, name) VALUES (39, '1118');
INSERT INTO model (brand_id, name) VALUES (39, '1119');
INSERT INTO model (brand_id, name) VALUES (39, '1200');
INSERT INTO model (brand_id, name) VALUES (39, '1300');
INSERT INTO model (brand_id, name) VALUES (39, '1500');
INSERT INTO model (brand_id, name) VALUES (39, '2101');
INSERT INTO model (brand_id, name) VALUES (39, '2103');
INSERT INTO model (brand_id, name) VALUES (39, '2104');
INSERT INTO model (brand_id, name) VALUES (39, '2105');
INSERT INTO model (brand_id, name) VALUES (39, '2106');
INSERT INTO model (brand_id, name) VALUES (39, '2107');
INSERT INTO model (brand_id, name) VALUES (39, '2108');
INSERT INTO model (brand_id, name) VALUES (39, '2109');
INSERT INTO model (brand_id, name) VALUES (39, '2110');
INSERT INTO model (brand_id, name) VALUES (39, '2111');
INSERT INTO model (brand_id, name) VALUES (39, '2112');
INSERT INTO model (brand_id, name) VALUES (39, '2170');
INSERT INTO model (brand_id, name) VALUES (39, 'Aleko');
INSERT INTO model (brand_id, name) VALUES (39, 'Forma');
INSERT INTO model (brand_id, name) VALUES (39, 'Granta');
INSERT INTO model (brand_id, name) VALUES (39, 'Kalina');
INSERT INTO model (brand_id, name) VALUES (39, 'Niva');
INSERT INTO model (brand_id, name) VALUES (39, 'Nova');
INSERT INTO model (brand_id, name) VALUES (39, 'Priora');
INSERT INTO model (brand_id, name) VALUES (39, 'Samara');
INSERT INTO brand (name) VALUES ('McLaren');
INSERT INTO model (brand_id, name) VALUES (40, '570 GT');
INSERT INTO model (brand_id, name) VALUES (40, '570S Coupe');
INSERT INTO model (brand_id, name) VALUES (40, '570S Spider');
INSERT INTO model (brand_id, name) VALUES (40, '600LT Coupe');
INSERT INTO model (brand_id, name) VALUES (40, '600LT Spider');
INSERT INTO model (brand_id, name) VALUES (40, '650S');
INSERT INTO model (brand_id, name) VALUES (40, '720S Coupe');
INSERT INTO model (brand_id, name) VALUES (40, '720S Spider');
INSERT INTO model (brand_id, name) VALUES (40, 'Altul');
INSERT INTO model (brand_id, name) VALUES (40, 'MP4-12C');
INSERT INTO brand (name) VALUES ('Maserati');
INSERT INTO model (brand_id, name) VALUES (41, '222');
INSERT INTO model (brand_id, name) VALUES (41, '224');
INSERT INTO model (brand_id, name) VALUES (41, '228');
INSERT INTO model (brand_id, name) VALUES (41, '418');
INSERT INTO model (brand_id, name) VALUES (41, '420');
INSERT INTO model (brand_id, name) VALUES (41, '422');
INSERT INTO model (brand_id, name) VALUES (41, '424');
INSERT INTO model (brand_id, name) VALUES (41, '3200');
INSERT INTO model (brand_id, name) VALUES (41, '4200');
INSERT INTO model (brand_id, name) VALUES (41, 'Biturbo');
INSERT INTO model (brand_id, name) VALUES (41, 'Coupe');
INSERT INTO model (brand_id, name) VALUES (41, 'Ghibli');
INSERT INTO model (brand_id, name) VALUES (41, 'GranCabrio');
INSERT INTO model (brand_id, name) VALUES (41, 'Gransport');
INSERT INTO model (brand_id, name) VALUES (41, 'GranTurismo');
INSERT INTO model (brand_id, name) VALUES (41, 'Indy');
INSERT INTO model (brand_id, name) VALUES (41, 'Karif');
INSERT INTO model (brand_id, name) VALUES (41, 'Levante');
INSERT INTO model (brand_id, name) VALUES (41, 'MC12');
INSERT INTO model (brand_id, name) VALUES (41, 'MC Stradale');
INSERT INTO model (brand_id, name) VALUES (41, 'Merak');
INSERT INTO model (brand_id, name) VALUES (41, 'Quattroporte');
INSERT INTO model (brand_id, name) VALUES (41, 'Shamal');
INSERT INTO model (brand_id, name) VALUES (41, 'Spyder');
INSERT INTO brand (name) VALUES ('Mazda');
INSERT INTO model (brand_id, name) VALUES (42, '2');
INSERT INTO model (brand_id, name) VALUES (42, '3');
INSERT INTO model (brand_id, name) VALUES (42, '5');
INSERT INTO model (brand_id, name) VALUES (42, '6');
INSERT INTO model (brand_id, name) VALUES (42, '121');
INSERT INTO model (brand_id, name) VALUES (42, '323');
INSERT INTO model (brand_id, name) VALUES (42, '323F');
INSERT INTO model (brand_id, name) VALUES (42, '626');
INSERT INTO model (brand_id, name) VALUES (42, '929');
INSERT INTO model (brand_id, name) VALUES (42, 'Bongo');
INSERT INTO model (brand_id, name) VALUES (42, 'BT-50');
INSERT INTO model (brand_id, name) VALUES (42, 'CX-3');
INSERT INTO model (brand_id, name) VALUES (42, 'CX-5');
INSERT INTO model (brand_id, name) VALUES (42, 'CX-7');
INSERT INTO model (brand_id, name) VALUES (42, 'CX-9');
INSERT INTO model (brand_id, name) VALUES (42, 'CX-30');
INSERT INTO model (brand_id, name) VALUES (42, 'Demio');
INSERT INTO model (brand_id, name) VALUES (42, 'Millenia');
INSERT INTO model (brand_id, name) VALUES (42, 'MPV');
INSERT INTO model (brand_id, name) VALUES (42, 'MX-3');
INSERT INTO model (brand_id, name) VALUES (42, 'MX-5');
INSERT INTO model (brand_id, name) VALUES (42, 'MX-6');
INSERT INTO model (brand_id, name) VALUES (42, 'Seria B');
INSERT INTO model (brand_id, name) VALUES (42, 'Seria E');
INSERT INTO model (brand_id, name) VALUES (42, 'Tribute');
INSERT INTO model (brand_id, name) VALUES (42, 'Xedos');
INSERT INTO brand (name) VALUES ('Mercedes-Benz');
INSERT INTO model (brand_id, name) VALUES (43, '280');
INSERT INTO model (brand_id, name) VALUES (43, 'AMG GT');
INSERT INTO model (brand_id, name) VALUES (43, 'Citan');
INSERT INTO model (brand_id, name) VALUES (43, 'CL');
INSERT INTO model (brand_id, name) VALUES (43, 'CLA');
INSERT INTO model (brand_id, name) VALUES (43, 'CLC');
INSERT INTO model (brand_id, name) VALUES (43, 'CLK');
INSERT INTO model (brand_id, name) VALUES (43, 'CLS');
INSERT INTO model (brand_id, name) VALUES (43, 'EQC');
INSERT INTO model (brand_id, name) VALUES (43, 'EQV');
INSERT INTO model (brand_id, name) VALUES (43, 'GL');
INSERT INTO model (brand_id, name) VALUES (43, 'GLA');
INSERT INTO model (brand_id, name) VALUES (43, 'GLB');
INSERT INTO model (brand_id, name) VALUES (43, 'GLC');
INSERT INTO model (brand_id, name) VALUES (43, 'GLE');
INSERT INTO model (brand_id, name) VALUES (43, 'GLK');
INSERT INTO model (brand_id, name) VALUES (43, 'GLS');
INSERT INTO model (brand_id, name) VALUES (43, 'Klasa A');
INSERT INTO model (brand_id, name) VALUES (43, 'Klasa B');
INSERT INTO model (brand_id, name) VALUES (43, 'Klasa C');
INSERT INTO model (brand_id, name) VALUES (43, 'Klasa D');
INSERT INTO model (brand_id, name) VALUES (43, 'Klasa E');
INSERT INTO model (brand_id, name) VALUES (43, 'Klasa G');
INSERT INTO model (brand_id, name) VALUES (43, 'Klasa R');
INSERT INTO model (brand_id, name) VALUES (43, 'Klasa S');
INSERT INTO model (brand_id, name) VALUES (43, 'Klasa V');
INSERT INTO model (brand_id, name) VALUES (43, 'Klasa X');
INSERT INTO model (brand_id, name) VALUES (43, 'MB 100');
INSERT INTO model (brand_id, name) VALUES (43, 'ML');
INSERT INTO model (brand_id, name) VALUES (43, 'Monarch');
INSERT INTO model (brand_id, name) VALUES (43, 'SL');
INSERT INTO model (brand_id, name) VALUES (43, 'SLC');
INSERT INTO model (brand_id, name) VALUES (43, 'SLK');
INSERT INTO model (brand_id, name) VALUES (43, 'SLR');
INSERT INTO model (brand_id, name) VALUES (43, 'SLS');
INSERT INTO model (brand_id, name) VALUES (43, 'Sprinter');
INSERT INTO model (brand_id, name) VALUES (43, 'Vaneo');
INSERT INTO model (brand_id, name) VALUES (43, 'Vario');
INSERT INTO model (brand_id, name) VALUES (43, 'Viano');
INSERT INTO model (brand_id, name) VALUES (43, 'Vito');
INSERT INTO model (brand_id, name) VALUES (43, 'W123');
INSERT INTO model (brand_id, name) VALUES (43, 'W124');
INSERT INTO model (brand_id, name) VALUES (43, 'W201');
INSERT INTO brand (name) VALUES ('Microcar');
INSERT INTO model (brand_id, name) VALUES (44, 'Cargo');
INSERT INTO model (brand_id, name) VALUES (44, 'DUE');
INSERT INTO model (brand_id, name) VALUES (44, 'DUE First');
INSERT INTO model (brand_id, name) VALUES (44, 'Flex');
INSERT INTO model (brand_id, name) VALUES (44, 'Highland X');
INSERT INTO model (brand_id, name) VALUES (44, 'Ligier');
INSERT INTO model (brand_id, name) VALUES (44, 'M.Cross');
INSERT INTO model (brand_id, name) VALUES (44, 'M.Go');
INSERT INTO model (brand_id, name) VALUES (44, 'MC');
INSERT INTO model (brand_id, name) VALUES (44, 'Virgo');
INSERT INTO brand (name) VALUES ('Mini');
INSERT INTO model (brand_id, name) VALUES (45, '1000');
INSERT INTO model (brand_id, name) VALUES (45, '1300');
INSERT INTO model (brand_id, name) VALUES (45, 'Clubman');
INSERT INTO model (brand_id, name) VALUES (45, 'Cooper');
INSERT INTO model (brand_id, name) VALUES (45, 'Cooper S');
INSERT INTO model (brand_id, name) VALUES (45, 'Countryman');
INSERT INTO model (brand_id, name) VALUES (45, 'ONE');
INSERT INTO model (brand_id, name) VALUES (45, 'Paceman');
INSERT INTO brand (name) VALUES ('Mitsubishi');
INSERT INTO model (brand_id, name) VALUES (46, '3000GT');
INSERT INTO model (brand_id, name) VALUES (46, 'ASX');
INSERT INTO model (brand_id, name) VALUES (46, 'Canter');
INSERT INTO model (brand_id, name) VALUES (46, 'Carisma');
INSERT INTO model (brand_id, name) VALUES (46, 'Cold');
INSERT INTO model (brand_id, name) VALUES (46, 'Cordia');
INSERT INTO model (brand_id, name) VALUES (46, 'Cosmos');
INSERT INTO model (brand_id, name) VALUES (46, 'Diamente');
INSERT INTO model (brand_id, name) VALUES (46, 'Eclipse');
INSERT INTO model (brand_id, name) VALUES (46, 'Eclipse Cross');
INSERT INTO model (brand_id, name) VALUES (46, 'Endeavor');
INSERT INTO model (brand_id, name) VALUES (46, 'FTO');
INSERT INTO model (brand_id, name) VALUES (46, 'Gallant');
INSERT INTO model (brand_id, name) VALUES (46, 'Galloper');
INSERT INTO model (brand_id, name) VALUES (46, 'Grandis');
INSERT INTO model (brand_id, name) VALUES (46, 'i-MiEV');
INSERT INTO model (brand_id, name) VALUES (46, 'L200');
INSERT INTO model (brand_id, name) VALUES (46, 'L300');
INSERT INTO model (brand_id, name) VALUES (46, 'L400');
INSERT INTO model (brand_id, name) VALUES (46, 'Lancer');
INSERT INTO model (brand_id, name) VALUES (46, 'Lancer Evolution');
INSERT INTO model (brand_id, name) VALUES (46, 'Montero');
INSERT INTO model (brand_id, name) VALUES (46, 'Outlander');
INSERT INTO model (brand_id, name) VALUES (46, 'Pajero');
INSERT INTO model (brand_id, name) VALUES (46, 'Pajero Pinin');
INSERT INTO model (brand_id, name) VALUES (46, 'Santamo');
INSERT INTO model (brand_id, name) VALUES (46, 'Sapporo');
INSERT INTO model (brand_id, name) VALUES (46, 'Sigma');
INSERT INTO model (brand_id, name) VALUES (46, 'Space Gear');
INSERT INTO model (brand_id, name) VALUES (46, 'Space Runner');
INSERT INTO model (brand_id, name) VALUES (46, 'Space Star');
INSERT INTO model (brand_id, name) VALUES (46, 'Space Wagon');
INSERT INTO model (brand_id, name) VALUES (46, 'Starion');
INSERT INTO model (brand_id, name) VALUES (46, 'Tredia');
INSERT INTO brand (name) VALUES ('Nissan');
INSERT INTO model (brand_id, name) VALUES (47, '100 NX');
INSERT INTO model (brand_id, name) VALUES (47, '200 SX');
INSERT INTO model (brand_id, name) VALUES (47, '240 SX');
INSERT INTO model (brand_id, name) VALUES (47, '280 ZX');
INSERT INTO model (brand_id, name) VALUES (47, '300 ZX');
INSERT INTO model (brand_id, name) VALUES (47, '350 Z');
INSERT INTO model (brand_id, name) VALUES (47, '370 Z');
INSERT INTO model (brand_id, name) VALUES (47, 'Almera');
INSERT INTO model (brand_id, name) VALUES (47, 'Almera Tino');
INSERT INTO model (brand_id, name) VALUES (47, 'Altima');
INSERT INTO model (brand_id, name) VALUES (47, 'Armada');
INSERT INTO model (brand_id, name) VALUES (47, 'Bluebird');
INSERT INTO model (brand_id, name) VALUES (47, 'Cherry');
INSERT INTO model (brand_id, name) VALUES (47, 'Cube');
INSERT INTO model (brand_id, name) VALUES (47, 'Frontier');
INSERT INTO model (brand_id, name) VALUES (47, 'GT-R');
INSERT INTO model (brand_id, name) VALUES (47, 'Interstar');
INSERT INTO model (brand_id, name) VALUES (47, 'Juke');
INSERT INTO model (brand_id, name) VALUES (47, 'King Cab');
INSERT INTO model (brand_id, name) VALUES (47, 'Kubistar');
INSERT INTO model (brand_id, name) VALUES (47, 'Laurel');
INSERT INTO model (brand_id, name) VALUES (47, 'Leaf');
INSERT INTO model (brand_id, name) VALUES (47, 'Maxima');
INSERT INTO model (brand_id, name) VALUES (47, 'Micra');
INSERT INTO model (brand_id, name) VALUES (47, 'Murano');
INSERT INTO model (brand_id, name) VALUES (47, 'Navara');
INSERT INTO model (brand_id, name) VALUES (47, 'Note');
INSERT INTO model (brand_id, name) VALUES (47, 'NP300 Pickup');
INSERT INTO model (brand_id, name) VALUES (47, 'NV200');
INSERT INTO model (brand_id, name) VALUES (47, 'NV300');
INSERT INTO model (brand_id, name) VALUES (47, 'NV400');
INSERT INTO model (brand_id, name) VALUES (47, 'Pathfinder');
INSERT INTO model (brand_id, name) VALUES (47, 'Patrol');
INSERT INTO model (brand_id, name) VALUES (47, 'Pickup');
INSERT INTO model (brand_id, name) VALUES (47, 'Pixo');
INSERT INTO model (brand_id, name) VALUES (47, 'Prairie');
INSERT INTO model (brand_id, name) VALUES (47, 'Primastar');
INSERT INTO model (brand_id, name) VALUES (47, 'Primera');
INSERT INTO model (brand_id, name) VALUES (47, 'Pulsar');
INSERT INTO model (brand_id, name) VALUES (47, 'Qashqui');
INSERT INTO model (brand_id, name) VALUES (47, 'Qashqui+2');
INSERT INTO model (brand_id, name) VALUES (47, 'Quest');
INSERT INTO model (brand_id, name) VALUES (47, 'Rogue');
INSERT INTO model (brand_id, name) VALUES (47, 'Sentra');
INSERT INTO model (brand_id, name) VALUES (47, 'Serena');
INSERT INTO model (brand_id, name) VALUES (47, 'Silvia');
INSERT INTO model (brand_id, name) VALUES (47, 'Skyline');
INSERT INTO model (brand_id, name) VALUES (47, 'Stanza');
INSERT INTO model (brand_id, name) VALUES (47, 'Sunny');
INSERT INTO model (brand_id, name) VALUES (47, 'Terrano');
INSERT INTO model (brand_id, name) VALUES (47, 'Tiida');
INSERT INTO model (brand_id, name) VALUES (47, 'Titan');
INSERT INTO model (brand_id, name) VALUES (47, 'Trade');
INSERT INTO model (brand_id, name) VALUES (47, 'Urvan');
INSERT INTO model (brand_id, name) VALUES (47, 'Vanette');
INSERT INTO model (brand_id, name) VALUES (47, 'X-Trail');
INSERT INTO model (brand_id, name) VALUES (47, 'Xterra');
INSERT INTO brand (name) VALUES ('Opel');
INSERT INTO model (brand_id, name) VALUES (48, 'Adam');
INSERT INTO model (brand_id, name) VALUES (48, 'Agila');
INSERT INTO model (brand_id, name) VALUES (48, 'Ampera');
INSERT INTO model (brand_id, name) VALUES (48, 'Antara');
INSERT INTO model (brand_id, name) VALUES (48, 'Arena');
INSERT INTO model (brand_id, name) VALUES (48, 'Ascona');
INSERT INTO model (brand_id, name) VALUES (48, 'Astra');
INSERT INTO model (brand_id, name) VALUES (48, 'Calibra');
INSERT INTO model (brand_id, name) VALUES (48, 'Campo');
INSERT INTO model (brand_id, name) VALUES (48, 'Cascada');
INSERT INTO model (brand_id, name) VALUES (48, 'Combo');
INSERT INTO model (brand_id, name) VALUES (48, 'Commodore');
INSERT INTO model (brand_id, name) VALUES (48, 'Corsa');
INSERT INTO model (brand_id, name) VALUES (48, 'Crossland X');
INSERT INTO model (brand_id, name) VALUES (48, 'Diplomat');
INSERT INTO model (brand_id, name) VALUES (48, 'Frontera');
INSERT INTO model (brand_id, name) VALUES (48, 'Grandland X');
INSERT INTO model (brand_id, name) VALUES (48, 'GT');
INSERT INTO model (brand_id, name) VALUES (48, 'Insignia');
INSERT INTO model (brand_id, name) VALUES (48, 'Kadett');
INSERT INTO model (brand_id, name) VALUES (48, 'Karl');
INSERT INTO model (brand_id, name) VALUES (48, 'Manta');
INSERT INTO model (brand_id, name) VALUES (48, 'Meriva');
INSERT INTO model (brand_id, name) VALUES (48, 'Mokka');
INSERT INTO model (brand_id, name) VALUES (48, 'Monterey');
INSERT INTO model (brand_id, name) VALUES (48, 'Monza');
INSERT INTO model (brand_id, name) VALUES (48, 'Movano');
INSERT INTO model (brand_id, name) VALUES (48, 'Nova');
INSERT INTO model (brand_id, name) VALUES (48, 'Omega');
INSERT INTO model (brand_id, name) VALUES (48, 'Pick up Sportcap');
INSERT INTO model (brand_id, name) VALUES (48, 'Record');
INSERT INTO model (brand_id, name) VALUES (48, 'Senator');
INSERT INTO model (brand_id, name) VALUES (48, 'Signum');
INSERT INTO model (brand_id, name) VALUES (48, 'Sintra');
INSERT INTO model (brand_id, name) VALUES (48, 'Speedster');
INSERT INTO model (brand_id, name) VALUES (48, 'Tigra');
INSERT INTO model (brand_id, name) VALUES (48, 'Vectra');
INSERT INTO model (brand_id, name) VALUES (48, 'Vivaro');
INSERT INTO model (brand_id, name) VALUES (48, 'Zafira');
INSERT INTO brand (name) VALUES ('Peugeot');
INSERT INTO model (brand_id, name) VALUES (49, '104');
INSERT INTO model (brand_id, name) VALUES (49, '106');
INSERT INTO model (brand_id, name) VALUES (49, '107');
INSERT INTO model (brand_id, name) VALUES (49, '108');
INSERT INTO model (brand_id, name) VALUES (49, '204');
INSERT INTO model (brand_id, name) VALUES (49, '205');
INSERT INTO model (brand_id, name) VALUES (49, '206');
INSERT INTO model (brand_id, name) VALUES (49, '206 CC');
INSERT INTO model (brand_id, name) VALUES (49, '206 plus');
INSERT INTO model (brand_id, name) VALUES (49, '206 plus');
INSERT INTO model (brand_id, name) VALUES (49, '207');
INSERT INTO model (brand_id, name) VALUES (49, '207 CC');
INSERT INTO model (brand_id, name) VALUES (49, '208');
INSERT INTO model (brand_id, name) VALUES (49, '301');
INSERT INTO model (brand_id, name) VALUES (49, '304');
INSERT INTO model (brand_id, name) VALUES (49, '305');
INSERT INTO model (brand_id, name) VALUES (49, '306');
INSERT INTO model (brand_id, name) VALUES (49, '307');
INSERT INTO model (brand_id, name) VALUES (49, '307 CC');
INSERT INTO model (brand_id, name) VALUES (49, '308');
INSERT INTO model (brand_id, name) VALUES (49, '308 CC');
INSERT INTO model (brand_id, name) VALUES (49, '309');
INSERT INTO model (brand_id, name) VALUES (49, '395');
INSERT INTO model (brand_id, name) VALUES (49, '404');
INSERT INTO model (brand_id, name) VALUES (49, '405');
INSERT INTO model (brand_id, name) VALUES (49, '406');
INSERT INTO model (brand_id, name) VALUES (49, '407');
INSERT INTO model (brand_id, name) VALUES (49, '504');
INSERT INTO model (brand_id, name) VALUES (49, '505');
INSERT INTO model (brand_id, name) VALUES (49, '508');
INSERT INTO model (brand_id, name) VALUES (49, '604');
INSERT INTO model (brand_id, name) VALUES (49, '605');
INSERT INTO model (brand_id, name) VALUES (49, '607');
INSERT INTO model (brand_id, name) VALUES (49, '806');
INSERT INTO model (brand_id, name) VALUES (49, '807');
INSERT INTO model (brand_id, name) VALUES (49, '1007');
INSERT INTO model (brand_id, name) VALUES (49, '2008');
INSERT INTO model (brand_id, name) VALUES (49, '3008');
INSERT INTO model (brand_id, name) VALUES (49, '4007');
INSERT INTO model (brand_id, name) VALUES (49, '4008');
INSERT INTO model (brand_id, name) VALUES (49, '5008');
INSERT INTO model (brand_id, name) VALUES (49, 'Bipper');
INSERT INTO model (brand_id, name) VALUES (49, 'Boxer');
INSERT INTO model (brand_id, name) VALUES (49, 'Expert');
INSERT INTO model (brand_id, name) VALUES (49, 'iOn');
INSERT INTO model (brand_id, name) VALUES (49, 'Partner');
INSERT INTO model (brand_id, name) VALUES (49, 'RCZ');
INSERT INTO model (brand_id, name) VALUES (49, 'Rifter');
INSERT INTO model (brand_id, name) VALUES (49, 'Traveller');
INSERT INTO brand (name) VALUES ('Plymouth');
INSERT INTO model (brand_id, name) VALUES (50, 'Belvedere');
INSERT INTO model (brand_id, name) VALUES (50, 'Caravelle');
INSERT INTO model (brand_id, name) VALUES (50, 'Duster');
INSERT INTO model (brand_id, name) VALUES (50, 'Fury');
INSERT INTO model (brand_id, name) VALUES (50, 'Grand Voyager');
INSERT INTO model (brand_id, name) VALUES (50, 'Gran Fury');
INSERT INTO model (brand_id, name) VALUES (50, 'GTX');
INSERT INTO model (brand_id, name) VALUES (50, 'Horizon');
INSERT INTO model (brand_id, name) VALUES (50, 'Laser');
INSERT INTO model (brand_id, name) VALUES (50, 'Prowler');
INSERT INTO model (brand_id, name) VALUES (50, 'Road Runner');
INSERT INTO model (brand_id, name) VALUES (50, 'Satellite');
INSERT INTO model (brand_id, name) VALUES (50, 'Superbird');
INSERT INTO model (brand_id, name) VALUES (50, 'Turismo');
INSERT INTO model (brand_id, name) VALUES (50, 'Valiant');
INSERT INTO model (brand_id, name) VALUES (50, 'Voyager');
INSERT INTO brand (name) VALUES ('Polonez');
INSERT INTO model (brand_id, name) VALUES (51, '1.5');
INSERT INTO model (brand_id, name) VALUES (51, '1.6');
INSERT INTO model (brand_id, name) VALUES (51, 'Atu');
INSERT INTO model (brand_id, name) VALUES (51, 'Caro');
INSERT INTO brand (name) VALUES ('Pontiac');
INSERT INTO model (brand_id, name) VALUES (52, '1000');
INSERT INTO model (brand_id, name) VALUES (52, '6000');
INSERT INTO model (brand_id, name) VALUES (52, 'Bonneville');
INSERT INTO model (brand_id, name) VALUES (52, 'Catalina');
INSERT INTO model (brand_id, name) VALUES (52, 'Chieftain');
INSERT INTO model (brand_id, name) VALUES (52, 'Fiero');
INSERT INTO model (brand_id, name) VALUES (52, 'Firebird');
INSERT INTO model (brand_id, name) VALUES (52, 'G6');
INSERT INTO model (brand_id, name) VALUES (52, 'Grand-Am');
INSERT INTO model (brand_id, name) VALUES (52, 'Grand-Prix');
INSERT INTO model (brand_id, name) VALUES (52, 'GTO');
INSERT INTO model (brand_id, name) VALUES (52, 'Le Mans');
INSERT INTO model (brand_id, name) VALUES (52, 'Montana');
INSERT INTO model (brand_id, name) VALUES (52, 'Montana');
INSERT INTO model (brand_id, name) VALUES (52, 'Solstice');
INSERT INTO model (brand_id, name) VALUES (52, 'Sunbird');
INSERT INTO model (brand_id, name) VALUES (52, 'Trans Am');
INSERT INTO model (brand_id, name) VALUES (52, 'Trans Sport');
INSERT INTO model (brand_id, name) VALUES (52, 'Vibe');
INSERT INTO brand (name) VALUES ('Porsche');
INSERT INTO model (brand_id, name) VALUES (53, '356');
INSERT INTO model (brand_id, name) VALUES (53, '718 Boxter');
INSERT INTO model (brand_id, name) VALUES (53, '718 Cayman');
INSERT INTO model (brand_id, name) VALUES (53, '718 Spyder');
INSERT INTO model (brand_id, name) VALUES (53, '911');
INSERT INTO model (brand_id, name) VALUES (53, '912');
INSERT INTO model (brand_id, name) VALUES (53, '914');
INSERT INTO model (brand_id, name) VALUES (53, '924');
INSERT INTO model (brand_id, name) VALUES (53, '928');
INSERT INTO model (brand_id, name) VALUES (53, '944');
INSERT INTO model (brand_id, name) VALUES (53, '959');
INSERT INTO model (brand_id, name) VALUES (53, '962');
INSERT INTO model (brand_id, name) VALUES (53, '969');
INSERT INTO model (brand_id, name) VALUES (53, 'Boxter');
INSERT INTO model (brand_id, name) VALUES (53, 'Carrera GT');
INSERT INTO model (brand_id, name) VALUES (53, 'Cayenne');
INSERT INTO model (brand_id, name) VALUES (53, 'Cayman');
INSERT INTO model (brand_id, name) VALUES (53, 'Macan');
INSERT INTO model (brand_id, name) VALUES (53, 'Panamera');
INSERT INTO model (brand_id, name) VALUES (53, 'Taycan');
INSERT INTO brand (name) VALUES ('Renault');
INSERT INTO model (brand_id, name) VALUES (54, '4');
INSERT INTO model (brand_id, name) VALUES (54, '5');
INSERT INTO model (brand_id, name) VALUES (54, '8');
INSERT INTO model (brand_id, name) VALUES (54, '9');
INSERT INTO model (brand_id, name) VALUES (54, '10');
INSERT INTO model (brand_id, name) VALUES (54, '11');
INSERT INTO model (brand_id, name) VALUES (54, '12');
INSERT INTO model (brand_id, name) VALUES (54, '14');
INSERT INTO model (brand_id, name) VALUES (54, '18');
INSERT INTO model (brand_id, name) VALUES (54, '19');
INSERT INTO model (brand_id, name) VALUES (54, '20');
INSERT INTO model (brand_id, name) VALUES (54, '21');
INSERT INTO model (brand_id, name) VALUES (54, '25');
INSERT INTO model (brand_id, name) VALUES (54, '30');
INSERT INTO model (brand_id, name) VALUES (54, 'Alaskan');
INSERT INTO model (brand_id, name) VALUES (54, 'Aventime');
INSERT INTO model (brand_id, name) VALUES (54, 'Captur');
INSERT INTO model (brand_id, name) VALUES (54, 'Clio');
INSERT INTO model (brand_id, name) VALUES (54, 'Coupe');
INSERT INTO model (brand_id, name) VALUES (54, 'Espace');
INSERT INTO model (brand_id, name) VALUES (54, 'Express');
INSERT INTO model (brand_id, name) VALUES (54, 'Fluence');
INSERT INTO model (brand_id, name) VALUES (54, 'Fuego');
INSERT INTO model (brand_id, name) VALUES (54, 'Grand Espace');
INSERT INTO model (brand_id, name) VALUES (54, 'Grand Scenic');
INSERT INTO model (brand_id, name) VALUES (54, 'Kadjar');
INSERT INTO model (brand_id, name) VALUES (54, 'Kangoo');
INSERT INTO model (brand_id, name) VALUES (54, 'Koleos');
INSERT INTO model (brand_id, name) VALUES (54, 'Laguna');
INSERT INTO model (brand_id, name) VALUES (54, 'Latitude');
INSERT INTO model (brand_id, name) VALUES (54, 'Master');
INSERT INTO model (brand_id, name) VALUES (54, 'Megane');
INSERT INTO model (brand_id, name) VALUES (54, 'Modus');
INSERT INTO model (brand_id, name) VALUES (54, 'Safrane');
INSERT INTO model (brand_id, name) VALUES (54, 'Scenic');
INSERT INTO model (brand_id, name) VALUES (54, 'Scenic Conquest');
INSERT INTO model (brand_id, name) VALUES (54, 'Scenic RX4');
INSERT INTO model (brand_id, name) VALUES (54, 'Symbol');
INSERT INTO model (brand_id, name) VALUES (54, 'Talisman');
INSERT INTO model (brand_id, name) VALUES (54, 'Thalia');
INSERT INTO model (brand_id, name) VALUES (54, 'Trafic');
INSERT INTO model (brand_id, name) VALUES (54, 'Twingo');
INSERT INTO model (brand_id, name) VALUES (54, 'Twizy');
INSERT INTO model (brand_id, name) VALUES (54, 'Vel Satis');
INSERT INTO model (brand_id, name) VALUES (54, 'Wind');
INSERT INTO model (brand_id, name) VALUES (54, 'Zoe');
INSERT INTO brand (name) VALUES ('Rolls-Royce');
INSERT INTO model (brand_id, name) VALUES (55, 'Corniche');
INSERT INTO model (brand_id, name) VALUES (55, 'Cullinan');
INSERT INTO model (brand_id, name) VALUES (55, 'Flying Spur');
INSERT INTO model (brand_id, name) VALUES (55, 'Ghost');
INSERT INTO model (brand_id, name) VALUES (55, 'Park Ward');
INSERT INTO model (brand_id, name) VALUES (55, 'Phantom');
INSERT INTO model (brand_id, name) VALUES (55, 'Silver Cloud');
INSERT INTO model (brand_id, name) VALUES (55, 'Silver Down');
INSERT INTO model (brand_id, name) VALUES (55, 'Silver Seraph');
INSERT INTO model (brand_id, name) VALUES (55, 'Silver Shadow');
INSERT INTO model (brand_id, name) VALUES (55, 'Silver Spirit');
INSERT INTO model (brand_id, name) VALUES (55, 'Silver Spur');
INSERT INTO model (brand_id, name) VALUES (55, 'Touring Limousine');
INSERT INTO model (brand_id, name) VALUES (55, 'Wraith');
INSERT INTO brand (name) VALUES ('Rover');
INSERT INTO model (brand_id, name) VALUES (56, '25');
INSERT INTO model (brand_id, name) VALUES (56, '45');
INSERT INTO model (brand_id, name) VALUES (56, '75');
INSERT INTO model (brand_id, name) VALUES (56, '100');
INSERT INTO model (brand_id, name) VALUES (56, '111');
INSERT INTO model (brand_id, name) VALUES (56, '114');
INSERT INTO model (brand_id, name) VALUES (56, '115');
INSERT INTO model (brand_id, name) VALUES (56, '200');
INSERT INTO model (brand_id, name) VALUES (56, '213');
INSERT INTO model (brand_id, name) VALUES (56, '214');
INSERT INTO model (brand_id, name) VALUES (56, '216');
INSERT INTO model (brand_id, name) VALUES (56, '218');
INSERT INTO model (brand_id, name) VALUES (56, '220');
INSERT INTO model (brand_id, name) VALUES (56, '400');
INSERT INTO model (brand_id, name) VALUES (56, '414');
INSERT INTO model (brand_id, name) VALUES (56, '416');
INSERT INTO model (brand_id, name) VALUES (56, '418');
INSERT INTO model (brand_id, name) VALUES (56, '420');
INSERT INTO model (brand_id, name) VALUES (56, '600');
INSERT INTO model (brand_id, name) VALUES (56, '618');
INSERT INTO model (brand_id, name) VALUES (56, '620');
INSERT INTO model (brand_id, name) VALUES (56, '623');
INSERT INTO model (brand_id, name) VALUES (56, '800');
INSERT INTO model (brand_id, name) VALUES (56, '820');
INSERT INTO model (brand_id, name) VALUES (56, '825');
INSERT INTO model (brand_id, name) VALUES (56, '827');
INSERT INTO model (brand_id, name) VALUES (56, 'City Rover');
INSERT INTO model (brand_id, name) VALUES (56, 'Metro');
INSERT INTO model (brand_id, name) VALUES (56, 'MG');
INSERT INTO model (brand_id, name) VALUES (56, 'Mini');
INSERT INTO model (brand_id, name) VALUES (56, 'Montego');
INSERT INTO model (brand_id, name) VALUES (56, 'SD');
INSERT INTO model (brand_id, name) VALUES (56, 'Streetwise');
INSERT INTO brand (name) VALUES ('Saab');
INSERT INTO model (brand_id, name) VALUES (57, '9-2X');
INSERT INTO model (brand_id, name) VALUES (57, '9-3');
INSERT INTO model (brand_id, name) VALUES (57, '9-3X');
INSERT INTO model (brand_id, name) VALUES (57, '9-5');
INSERT INTO model (brand_id, name) VALUES (57, '9-7X');
INSERT INTO model (brand_id, name) VALUES (57, '90');
INSERT INTO model (brand_id, name) VALUES (57, '96');
INSERT INTO model (brand_id, name) VALUES (57, '99');
INSERT INTO model (brand_id, name) VALUES (57, '900');
INSERT INTO model (brand_id, name) VALUES (57, '9000');
INSERT INTO brand (name) VALUES ('Seat');
INSERT INTO model (brand_id, name) VALUES (58, 'Alhambra');
INSERT INTO model (brand_id, name) VALUES (58, 'Altea');
INSERT INTO model (brand_id, name) VALUES (58, 'Altea XL');
INSERT INTO model (brand_id, name) VALUES (58, 'Arona');
INSERT INTO model (brand_id, name) VALUES (58, 'Arosa');
INSERT INTO model (brand_id, name) VALUES (58, 'Ateca');
INSERT INTO model (brand_id, name) VALUES (58, 'Cordoba');
INSERT INTO model (brand_id, name) VALUES (58, 'Exeo');
INSERT INTO model (brand_id, name) VALUES (58, 'Ibiza');
INSERT INTO model (brand_id, name) VALUES (58, 'Inca');
INSERT INTO model (brand_id, name) VALUES (58, 'Leon');
INSERT INTO model (brand_id, name) VALUES (58, 'Malaga');
INSERT INTO model (brand_id, name) VALUES (58, 'Marbella');
INSERT INTO model (brand_id, name) VALUES (58, 'Mii');
INSERT INTO model (brand_id, name) VALUES (58, 'Ronda');
INSERT INTO model (brand_id, name) VALUES (58, 'Tarraco');
INSERT INTO model (brand_id, name) VALUES (58, 'Terra');
INSERT INTO model (brand_id, name) VALUES (58, 'Toledo');
INSERT INTO brand (name) VALUES ('Skoda');
INSERT INTO model (brand_id, name) VALUES (59, '100');
INSERT INTO model (brand_id, name) VALUES (59, '105');
INSERT INTO model (brand_id, name) VALUES (59, '120');
INSERT INTO model (brand_id, name) VALUES (59, '130');
INSERT INTO model (brand_id, name) VALUES (59, '135');
INSERT INTO model (brand_id, name) VALUES (59, 'Citigo');
INSERT INTO model (brand_id, name) VALUES (59, 'Fabia');
INSERT INTO model (brand_id, name) VALUES (59, 'Favorit');
INSERT INTO model (brand_id, name) VALUES (59, 'Felicia');
INSERT INTO model (brand_id, name) VALUES (59, 'Formman');
INSERT INTO model (brand_id, name) VALUES (59, 'Kamiq');
INSERT INTO model (brand_id, name) VALUES (59, 'Karoq');
INSERT INTO model (brand_id, name) VALUES (59, 'Kodiaq');
INSERT INTO model (brand_id, name) VALUES (59, 'Octavia');
INSERT INTO model (brand_id, name) VALUES (59, 'Praktik');
INSERT INTO model (brand_id, name) VALUES (59, 'Rapid');
INSERT INTO model (brand_id, name) VALUES (59, 'Roomster');
INSERT INTO model (brand_id, name) VALUES (59, 'Scala');
INSERT INTO model (brand_id, name) VALUES (59, 'Superb');
INSERT INTO model (brand_id, name) VALUES (59, 'Yeti');
INSERT INTO brand (name) VALUES ('Smart');
INSERT INTO model (brand_id, name) VALUES (60, 'Crossblade');
INSERT INTO model (brand_id, name) VALUES (60, 'Forfour');
INSERT INTO model (brand_id, name) VALUES (60, 'Fortwo');
INSERT INTO model (brand_id, name) VALUES (60, 'Roadster');
INSERT INTO model (brand_id, name) VALUES (60, 'Roomster');
INSERT INTO brand (name) VALUES ('SsangYong');
INSERT INTO model (brand_id, name) VALUES (61, 'Actyon');
INSERT INTO model (brand_id, name) VALUES (61, 'Family');
INSERT INTO model (brand_id, name) VALUES (61, 'Korando');
INSERT INTO model (brand_id, name) VALUES (61, 'Kyron');
INSERT INTO model (brand_id, name) VALUES (61, 'Musso');
INSERT INTO model (brand_id, name) VALUES (61, 'Rexton');
INSERT INTO model (brand_id, name) VALUES (61, 'Rodius');
INSERT INTO model (brand_id, name) VALUES (61, 'Tivoli');
INSERT INTO model (brand_id, name) VALUES (61, 'XLV');
INSERT INTO brand (name) VALUES ('Subaru');
INSERT INTO model (brand_id, name) VALUES (62, '1800 Coupe');
INSERT INTO model (brand_id, name) VALUES (62, 'B9 Tribeca');
INSERT INTO model (brand_id, name) VALUES (62, 'Baja');
INSERT INTO model (brand_id, name) VALUES (62, 'BRZ');
INSERT INTO model (brand_id, name) VALUES (62, 'Forester');
INSERT INTO model (brand_id, name) VALUES (62, 'G3X Justy');
INSERT INTO model (brand_id, name) VALUES (62, 'Impreza');
INSERT INTO model (brand_id, name) VALUES (62, 'Justy');
INSERT INTO model (brand_id, name) VALUES (62, 'Legacy');
INSERT INTO model (brand_id, name) VALUES (62, 'Leone');
INSERT INTO model (brand_id, name) VALUES (62, 'Levorg');
INSERT INTO model (brand_id, name) VALUES (62, 'Outback');
INSERT INTO model (brand_id, name) VALUES (62, 'SVX');
INSERT INTO model (brand_id, name) VALUES (62, 'Trezia');
INSERT INTO model (brand_id, name) VALUES (62, 'Tribeca');
INSERT INTO brand (name) VALUES ('Suzuki');
INSERT INTO model (brand_id, name) VALUES (63, 'Across');
INSERT INTO model (brand_id, name) VALUES (63, 'Alto');
INSERT INTO model (brand_id, name) VALUES (63, 'Baleno');
INSERT INTO model (brand_id, name) VALUES (63, 'Cappucino');
INSERT INTO model (brand_id, name) VALUES (63, 'Carry');
INSERT INTO model (brand_id, name) VALUES (63, 'Celerio');
INSERT INTO model (brand_id, name) VALUES (63, 'Grand Vitara');
INSERT INTO model (brand_id, name) VALUES (63, 'Ignis');
INSERT INTO model (brand_id, name) VALUES (63, 'Jimmny');
INSERT INTO model (brand_id, name) VALUES (63, 'Kizashi');
INSERT INTO model (brand_id, name) VALUES (63, 'Liana');
INSERT INTO model (brand_id, name) VALUES (63, 'LJ');
INSERT INTO model (brand_id, name) VALUES (63, 'Reno');
INSERT INTO model (brand_id, name) VALUES (63, 'Samuria');
INSERT INTO model (brand_id, name) VALUES (63, 'SJ');
INSERT INTO model (brand_id, name) VALUES (63, 'Splash');
INSERT INTO model (brand_id, name) VALUES (63, 'Super-Carry');
INSERT INTO model (brand_id, name) VALUES (63, 'Swace');
INSERT INTO model (brand_id, name) VALUES (63, 'Swift');
INSERT INTO model (brand_id, name) VALUES (63, 'SX4');
INSERT INTO model (brand_id, name) VALUES (63, 'SX4 S-Cross');
INSERT INTO model (brand_id, name) VALUES (63, 'Vitara');
INSERT INTO model (brand_id, name) VALUES (63, 'Wagon R+');
INSERT INTO model (brand_id, name) VALUES (63, 'X-90');
INSERT INTO model (brand_id, name) VALUES (63, 'XL7');
INSERT INTO brand (name) VALUES ('Tata');
INSERT INTO model (brand_id, name) VALUES (64, 'Indica');
INSERT INTO model (brand_id, name) VALUES (64, 'Indigo');
INSERT INTO model (brand_id, name) VALUES (64, 'Nano');
INSERT INTO model (brand_id, name) VALUES (64, 'Safari');
INSERT INTO model (brand_id, name) VALUES (64, 'Xenon');
INSERT INTO brand (name) VALUES ('Toyota');
INSERT INTO model (brand_id, name) VALUES (65, '4-Runner');
INSERT INTO model (brand_id, name) VALUES (65, 'Auris');
INSERT INTO model (brand_id, name) VALUES (65, 'Avalon');
INSERT INTO model (brand_id, name) VALUES (65, 'Avensis');
INSERT INTO model (brand_id, name) VALUES (65, 'Avensis Verso');
INSERT INTO model (brand_id, name) VALUES (65, 'Aygo');
INSERT INTO model (brand_id, name) VALUES (65, 'C-HR');
INSERT INTO model (brand_id, name) VALUES (65, 'Camry');
INSERT INTO model (brand_id, name) VALUES (65, 'Camry Solara');
INSERT INTO model (brand_id, name) VALUES (65, 'Carina');
INSERT INTO model (brand_id, name) VALUES (65, 'Celica');
INSERT INTO model (brand_id, name) VALUES (65, 'Corolla');
INSERT INTO model (brand_id, name) VALUES (65, 'Corolla Verso');
INSERT INTO model (brand_id, name) VALUES (65, 'Cressida');
INSERT INTO model (brand_id, name) VALUES (65, 'Crown');
INSERT INTO model (brand_id, name) VALUES (65, 'Dyna');
INSERT INTO model (brand_id, name) VALUES (65, 'FJ');
INSERT INTO model (brand_id, name) VALUES (65, 'GT86');
INSERT INTO model (brand_id, name) VALUES (65, 'Hiace');
INSERT INTO model (brand_id, name) VALUES (65, 'Highlander');
INSERT INTO model (brand_id, name) VALUES (65, 'Hilux');
INSERT INTO model (brand_id, name) VALUES (65, 'iQ');
INSERT INTO model (brand_id, name) VALUES (65, 'Land Cruiser');
INSERT INTO model (brand_id, name) VALUES (65, 'Lite-Ace');
INSERT INTO model (brand_id, name) VALUES (65, 'Matrix');
INSERT INTO model (brand_id, name) VALUES (65, 'Mirai');
INSERT INTO model (brand_id, name) VALUES (65, 'MR2');
INSERT INTO model (brand_id, name) VALUES (65, 'Paseo');
INSERT INTO model (brand_id, name) VALUES (65, 'Picnic');
INSERT INTO model (brand_id, name) VALUES (65, 'Previa');
INSERT INTO model (brand_id, name) VALUES (65, 'Prius');
INSERT INTO model (brand_id, name) VALUES (65, 'Prius+');
INSERT INTO model (brand_id, name) VALUES (65, 'Proace');
INSERT INTO model (brand_id, name) VALUES (65, 'Proace City Verso');
INSERT INTO model (brand_id, name) VALUES (65, 'Proace Verso');
INSERT INTO model (brand_id, name) VALUES (65, 'RAV4');
INSERT INTO model (brand_id, name) VALUES (65, 'Sequoia');
INSERT INTO model (brand_id, name) VALUES (65, 'Sienna');
INSERT INTO model (brand_id, name) VALUES (65, 'Starlet');
INSERT INTO model (brand_id, name) VALUES (65, 'Supra');
INSERT INTO model (brand_id, name) VALUES (65, 'Tacoma');
INSERT INTO model (brand_id, name) VALUES (65, 'Tercel');
INSERT INTO model (brand_id, name) VALUES (65, 'Tundra');
INSERT INTO model (brand_id, name) VALUES (65, 'Urban Cruiser');
INSERT INTO model (brand_id, name) VALUES (65, 'Venza');
INSERT INTO model (brand_id, name) VALUES (65, 'Verso');
INSERT INTO model (brand_id, name) VALUES (65, 'Verso S');
INSERT INTO model (brand_id, name) VALUES (65, 'Yaris');
INSERT INTO model (brand_id, name) VALUES (65, 'Yaris Verso');
INSERT INTO brand (name) VALUES ('UAZ');
INSERT INTO model (brand_id, name) VALUES (66, '452');
INSERT INTO model (brand_id, name) VALUES (66, '469 B');
INSERT INTO model (brand_id, name) VALUES (66, '3153');
INSERT INTO model (brand_id, name) VALUES (66, '3162');
INSERT INTO brand (name) VALUES ('Volkswagen');
INSERT INTO model (brand_id, name) VALUES (67, '181');
INSERT INTO model (brand_id, name) VALUES (67, 'Amarok');
INSERT INTO model (brand_id, name) VALUES (67, 'Arteon');
INSERT INTO model (brand_id, name) VALUES (67, 'Atlas');
INSERT INTO model (brand_id, name) VALUES (67, 'Beetle');
INSERT INTO model (brand_id, name) VALUES (67, 'Bora');
INSERT INTO model (brand_id, name) VALUES (67, 'Buggy');
INSERT INTO model (brand_id, name) VALUES (67, 'Caddy');
INSERT INTO model (brand_id, name) VALUES (67, 'California');
INSERT INTO model (brand_id, name) VALUES (67, 'Caravelle');
INSERT INTO model (brand_id, name) VALUES (67, 'CC');
INSERT INTO model (brand_id, name) VALUES (67, 'Corrado');
INSERT INTO model (brand_id, name) VALUES (67, 'Crafter');
INSERT INTO model (brand_id, name) VALUES (67, 'Eos');
INSERT INTO model (brand_id, name) VALUES (67, 'Fox');
INSERT INTO model (brand_id, name) VALUES (67, 'Garbus');
INSERT INTO model (brand_id, name) VALUES (67, 'Golf');
INSERT INTO model (brand_id, name) VALUES (67, 'Golf Plus');
INSERT INTO model (brand_id, name) VALUES (67, 'Golf Sportsvan');
INSERT INTO model (brand_id, name) VALUES (67, 'ID.3');
INSERT INTO model (brand_id, name) VALUES (67, 'Iltis');
INSERT INTO model (brand_id, name) VALUES (67, 'Jetta');
INSERT INTO model (brand_id, name) VALUES (67, 'Kafer');
INSERT INTO model (brand_id, name) VALUES (67, 'Karmann Ghia');
INSERT INTO model (brand_id, name) VALUES (67, 'LT');
INSERT INTO model (brand_id, name) VALUES (67, 'Lupo');
INSERT INTO model (brand_id, name) VALUES (67, 'Multivan');
INSERT INTO model (brand_id, name) VALUES (67, 'New Beetle');
INSERT INTO model (brand_id, name) VALUES (67, 'Passat');
INSERT INTO model (brand_id, name) VALUES (67, 'Passat CC');
INSERT INTO model (brand_id, name) VALUES (67, 'Phaeton');
INSERT INTO model (brand_id, name) VALUES (67, 'Polo');
INSERT INTO model (brand_id, name) VALUES (67, 'Routan');
INSERT INTO model (brand_id, name) VALUES (67, 'Santana');
INSERT INTO model (brand_id, name) VALUES (67, 'Scirocco');
INSERT INTO model (brand_id, name) VALUES (67, 'Sharan');
INSERT INTO model (brand_id, name) VALUES (67, 'T-Cross');
INSERT INTO model (brand_id, name) VALUES (67, 'T-Roc');
INSERT INTO model (brand_id, name) VALUES (67, 'Teramont');
INSERT INTO model (brand_id, name) VALUES (67, 'Tiguan');
INSERT INTO model (brand_id, name) VALUES (67, 'Tiguan Allspace');
INSERT INTO model (brand_id, name) VALUES (67, 'Tuareg');
INSERT INTO model (brand_id, name) VALUES (67, 'Touran');
INSERT INTO model (brand_id, name) VALUES (67, 'Transporter');
INSERT INTO model (brand_id, name) VALUES (67, 'Up!');
INSERT INTO model (brand_id, name) VALUES (67, 'Vento');
INSERT INTO brand (name) VALUES ('Volvo');
INSERT INTO model (brand_id, name) VALUES (68, '245');
INSERT INTO model (brand_id, name) VALUES (68, '262');
INSERT INTO model (brand_id, name) VALUES (68, '340');
INSERT INTO model (brand_id, name) VALUES (68, '744');
INSERT INTO model (brand_id, name) VALUES (68, '745');
INSERT INTO model (brand_id, name) VALUES (68, '780');
INSERT INTO model (brand_id, name) VALUES (68, '850');
INSERT INTO model (brand_id, name) VALUES (68, '855');
INSERT INTO model (brand_id, name) VALUES (68, '945');
INSERT INTO model (brand_id, name) VALUES (68, '965');
INSERT INTO model (brand_id, name) VALUES (68, 'C30');
INSERT INTO model (brand_id, name) VALUES (68, 'C70');
INSERT INTO model (brand_id, name) VALUES (68, 'Polar');
INSERT INTO model (brand_id, name) VALUES (68, 'S40');
INSERT INTO model (brand_id, name) VALUES (68, 'S60');
INSERT INTO model (brand_id, name) VALUES (68, 'S70');
INSERT INTO model (brand_id, name) VALUES (68, 'S80');
INSERT INTO model (brand_id, name) VALUES (68, 'S90');
INSERT INTO model (brand_id, name) VALUES (68, 'Seria 200');
INSERT INTO model (brand_id, name) VALUES (68, 'Seria 300');
INSERT INTO model (brand_id, name) VALUES (68, 'Seria 400');
INSERT INTO model (brand_id, name) VALUES (68, 'Seria 700');
INSERT INTO model (brand_id, name) VALUES (68, 'Seria 900');
INSERT INTO model (brand_id, name) VALUES (68, 'V40');
INSERT INTO model (brand_id, name) VALUES (68, 'V50');
INSERT INTO model (brand_id, name) VALUES (68, 'V60');
INSERT INTO model (brand_id, name) VALUES (68, 'V70');
INSERT INTO model (brand_id, name) VALUES (68, 'V90');
INSERT INTO model (brand_id, name) VALUES (68, 'XC 40');
INSERT INTO model (brand_id, name) VALUES (68, 'XC 60');
INSERT INTO model (brand_id, name) VALUES (68, 'XC 70');
INSERT INTO model (brand_id, name) VALUES (68, 'XC 90');
INSERT INTO brand (name) VALUES ('Wartburg');
INSERT INTO model (brand_id, name) VALUES (69, '1.3');
INSERT INTO model (brand_id, name) VALUES (69, '311');
INSERT INTO model (brand_id, name) VALUES (69, '312');
INSERT INTO model (brand_id, name) VALUES (69, '313');
INSERT INTO model (brand_id, name) VALUES (69, '353');

INSERT INTO engine (codename, fuel, capacity, horse_power, torque) VALUES ('RFN','BENZINE', 2000, 222, 200);
INSERT INTO engine (codename, fuel, capacity, horse_power, torque) VALUES ('RFN','BENZINE', 2000, 136, 170);
INSERT INTO engine (codename, fuel, capacity, horse_power, torque) VALUES ('BAM','BENZINE', 1781, 222, 280);

INSERT INTO user (email, password) VALUES ('damian@soltysiuk.pl', 'soltysiuk');

INSERT INTO car (model_id, variant, user_id, engine_id, register_number, description)
VALUES (315, 'supercharger', 1, 1, 'BS61654', 'amateur tuning car');
INSERT INTO car (model_id, variant, user_id, engine_id, register_number, description)
VALUES (315, 'exlusive', 1, 2, 'WI12344', 'serial car');